package emoji

var CategoryActivity = []string {
	"⚽️", // soccer ball, tags=[sports], aliases=[soccer]
	"🏀", // basketball, tags=[sports], aliases=[basketball]
	"🏈", // american football, tags=[sports], aliases=[football]
	"⚾️", // baseball, tags=[sports], aliases=[baseball]
	"🎾", // tennis, tags=[sports], aliases=[tennis]
	"🏐", // volleyball, tags=[], aliases=[volleyball]
	"🏉", // rugby football, tags=[], aliases=[rugby_football]
	"🎱", // pool 8 ball, tags=[pool billiards], aliases=[8ball]
	"🏓", // ping pong, tags=[], aliases=[ping_pong]
	"🏸", // badminton, tags=[], aliases=[badminton]
	"🥅", // goal net, tags=[], aliases=[goal_net]
	"🏒", // ice hockey, tags=[], aliases=[ice_hockey]
	"🏑", // field hockey, tags=[], aliases=[field_hockey]
	"🏏", // cricket, tags=[], aliases=[cricket]
	"⛳️", // flag in hole, tags=[], aliases=[golf]
	"🏹", // bow and arrow, tags=[archery], aliases=[bow_and_arrow]
	"🎣", // fishing pole, tags=[], aliases=[fishing_pole_and_fish]
	"🥊", // boxing glove, tags=[], aliases=[boxing_glove]
	"🥋", // martial arts uniform, tags=[], aliases=[martial_arts_uniform]
	"⛸", // ice skate, tags=[skating], aliases=[ice_skate]
	"🎿", // skis, tags=[], aliases=[ski]
	"⛷", // skier, tags=[], aliases=[skier]
	"🏂", // snowboarder, tags=[], aliases=[snowboarder]
	"🏋️‍♀️", // woman lifting weights, tags=[gym workout], aliases=[weight_lifting_woman]
	"🏋", // person lifting weights, tags=[gym workout], aliases=[weight_lifting_man]
	"🤺", // person fencing, tags=[], aliases=[person_fencing]
	"🤼‍♀", // women wrestling, tags=[], aliases=[women_wrestling]
	"🤼‍♂", // men wrestling, tags=[], aliases=[men_wrestling]
	"🤸‍♀", // woman cartwheeling, tags=[], aliases=[woman_cartwheeling]
	"🤸‍♂", // man cartwheeling, tags=[], aliases=[man_cartwheeling]
	"⛹️‍♀️", // woman bouncing ball, tags=[], aliases=[basketball_woman]
	"⛹", // person bouncing ball, tags=[], aliases=[basketball_man]
	"🤾‍♀", // woman playing handball, tags=[], aliases=[woman_playing_handball]
	"🤾‍♂", // man playing handball, tags=[], aliases=[man_playing_handball]
	"🏌️‍♀️", // woman golfing, tags=[], aliases=[golfing_woman]
	"🏌", // person golfing, tags=[], aliases=[golfing_man]
	"🏄‍♀", // woman surfing, tags=[], aliases=[surfing_woman]
	"🏄", // person surfing, tags=[], aliases=[surfing_man surfer]
	"🏊‍♀", // woman swimming, tags=[], aliases=[swimming_woman]
	"🏊", // person swimming, tags=[], aliases=[swimming_man swimmer]
	"🤽‍♀", // woman playing water polo, tags=[], aliases=[woman_playing_water_polo]
	"🤽‍♂", // man playing water polo, tags=[], aliases=[man_playing_water_polo]
	"🚣‍♀", // woman rowing boat, tags=[], aliases=[rowing_woman]
	"🚣", // person rowing boat, tags=[], aliases=[rowing_man rowboat]
	"🏇", // horse racing, tags=[], aliases=[horse_racing]
	"🚴‍♀", // woman biking, tags=[], aliases=[biking_woman]
	"🚴", // person biking, tags=[], aliases=[biking_man bicyclist]
	"🚵‍♀", // woman mountain biking, tags=[], aliases=[mountain_biking_woman]
	"🚵", // person mountain biking, tags=[], aliases=[mountain_biking_man mountain_bicyclist]
	"🎽", // running shirt, tags=[marathon], aliases=[running_shirt_with_sash]
	"🏅", // sports medal, tags=[gold winner], aliases=[medal_sports]
	"🎖", // military medal, tags=[], aliases=[medal_military]
	"🥇", // 1st place medal, tags=[gold], aliases=[1st_place_medal]
	"🥈", // 2nd place medal, tags=[silver], aliases=[2nd_place_medal]
	"🥉", // 3rd place medal, tags=[bronze], aliases=[3rd_place_medal]
	"🏆", // trophy, tags=[award contest winner], aliases=[trophy]
	"🏵", // rosette, tags=[], aliases=[rosette]
	"🎗", // reminder ribbon, tags=[], aliases=[reminder_ribbon]
	"🎫", // ticket, tags=[], aliases=[ticket]
	"🎟", // admission tickets, tags=[], aliases=[tickets]
	"🎪", // circus tent, tags=[], aliases=[circus_tent]
	"🤹‍♀", // woman juggling, tags=[], aliases=[woman_juggling]
	"🤹‍♂", // man juggling, tags=[], aliases=[man_juggling]
	"🎭", // performing arts, tags=[theater drama], aliases=[performing_arts]
	"🎨", // artist palette, tags=[design paint], aliases=[art]
	"🎬", // clapper board, tags=[film], aliases=[clapper]
	"🎤", // microphone, tags=[sing], aliases=[microphone]
	"🎧", // headphone, tags=[music earphones], aliases=[headphones]
	"🎼", // musical score, tags=[], aliases=[musical_score]
	"🎹", // musical keyboard, tags=[piano], aliases=[musical_keyboard]
	"🥁", // drum, tags=[], aliases=[drum]
	"🎷", // saxophone, tags=[], aliases=[saxophone]
	"🎺", // trumpet, tags=[], aliases=[trumpet]
	"🎸", // guitar, tags=[rock], aliases=[guitar]
	"🎻", // violin, tags=[], aliases=[violin]
	"🎲", // game die, tags=[dice gambling], aliases=[game_die]
	"🎯", // direct hit, tags=[target], aliases=[dart]
	"🎳", // bowling, tags=[], aliases=[bowling]
	"🎮", // video game, tags=[play controller console], aliases=[video_game]
	"🎰", // slot machine, tags=[], aliases=[slot_machine]
}
