package emojis

var CategoryPlaces = []string {
	"🚗", // automobile, tags=[], aliases=[car red_car]
	"🚕", // taxi, tags=[], aliases=[taxi]
	"🚙", // sport utility vehicle, tags=[], aliases=[blue_car]
	"🚌", // bus, tags=[], aliases=[bus]
	"🚎", // trolleybus, tags=[], aliases=[trolleybus]
	"🏎", // racing car, tags=[], aliases=[racing_car]
	"🚓", // police car, tags=[], aliases=[police_car]
	"🚑", // ambulance, tags=[], aliases=[ambulance]
	"🚒", // fire engine, tags=[], aliases=[fire_engine]
	"🚐", // minibus, tags=[], aliases=[minibus]
	"🚚", // delivery truck, tags=[], aliases=[truck]
	"🚛", // articulated lorry, tags=[], aliases=[articulated_lorry]
	"🚜", // tractor, tags=[], aliases=[tractor]
	"🛴", // kick scooter, tags=[], aliases=[kick_scooter]
	"🚲", // bicycle, tags=[bicycle], aliases=[bike]
	"🛵", // motor scooter, tags=[], aliases=[motor_scooter]
	"🏍", // motorcycle, tags=[], aliases=[motorcycle]
	"🚨", // police car light, tags=[911 emergency], aliases=[rotating_light]
	"🚔", // oncoming police car, tags=[], aliases=[oncoming_police_car]
	"🚍", // oncoming bus, tags=[], aliases=[oncoming_bus]
	"🚘", // oncoming automobile, tags=[], aliases=[oncoming_automobile]
	"🚖", // oncoming taxi, tags=[], aliases=[oncoming_taxi]
	"🚡", // aerial tramway, tags=[], aliases=[aerial_tramway]
	"🚠", // mountain cableway, tags=[], aliases=[mountain_cableway]
	"🚟", // suspension railway, tags=[], aliases=[suspension_railway]
	"🚃", // railway car, tags=[], aliases=[railway_car]
	"🚋", // tram car, tags=[], aliases=[train]
	"🚞", // mountain railway, tags=[], aliases=[mountain_railway]
	"🚝", // monorail, tags=[], aliases=[monorail]
	"🚄", // high-speed train, tags=[train], aliases=[bullettrain_side]
	"🚅", // high-speed train with bullet nose, tags=[train], aliases=[bullettrain_front]
	"🚈", // light rail, tags=[], aliases=[light_rail]
	"🚂", // locomotive, tags=[train], aliases=[steam_locomotive]
	"🚆", // train, tags=[], aliases=[train2]
	"🚇", // metro, tags=[], aliases=[metro]
	"🚊", // tram, tags=[], aliases=[tram]
	"🚉", // station, tags=[], aliases=[station]
	"🚁", // helicopter, tags=[], aliases=[helicopter]
	"🛩", // small airplane, tags=[flight], aliases=[small_airplane]
	"✈️", // airplane, tags=[flight], aliases=[airplane]
	"🛫", // airplane departure, tags=[], aliases=[flight_departure]
	"🛬", // airplane arrival, tags=[], aliases=[flight_arrival]
	"🚀", // rocket, tags=[ship launch], aliases=[rocket]
	"🛰", // satellite, tags=[orbit space], aliases=[artificial_satellite]
	"💺", // seat, tags=[], aliases=[seat]
	"🛶", // canoe, tags=[], aliases=[canoe]
	"⛵️", // sailboat, tags=[], aliases=[boat sailboat]
	"🛥", // motor boat, tags=[], aliases=[motor_boat]
	"🚤", // speedboat, tags=[ship], aliases=[speedboat]
	"🛳", // passenger ship, tags=[cruise], aliases=[passenger_ship]
	"⛴", // ferry, tags=[], aliases=[ferry]
	"🚢", // ship, tags=[], aliases=[ship]
	"⚓️", // anchor, tags=[ship], aliases=[anchor]
	"🚧", // construction, tags=[wip], aliases=[construction]
	"⛽️", // fuel pump, tags=[], aliases=[fuelpump]
	"🚏", // bus stop, tags=[], aliases=[busstop]
	"🚦", // vertical traffic light, tags=[semaphore], aliases=[vertical_traffic_light]
	"🚥", // horizontal traffic light, tags=[], aliases=[traffic_light]
	"🗺", // world map, tags=[travel], aliases=[world_map]
	"🗿", // moai, tags=[stone], aliases=[moyai]
	"🗽", // Statue of Liberty, tags=[], aliases=[statue_of_liberty]
	"⛲️", // fountain, tags=[], aliases=[fountain]
	"🗼", // Tokyo tower, tags=[], aliases=[tokyo_tower]
	"🏰", // castle, tags=[], aliases=[european_castle]
	"🏯", // Japanese castle, tags=[], aliases=[japanese_castle]
	"🏟", // stadium, tags=[], aliases=[stadium]
	"🎡", // ferris wheel, tags=[], aliases=[ferris_wheel]
	"🎢", // roller coaster, tags=[], aliases=[roller_coaster]
	"🎠", // carousel horse, tags=[], aliases=[carousel_horse]
	"⛱", // umbrella on ground, tags=[beach_umbrella], aliases=[parasol_on_ground]
	"🏖", // beach with umbrella, tags=[], aliases=[beach_umbrella]
	"🏝", // desert island, tags=[], aliases=[desert_island]
	"⛰", // mountain, tags=[], aliases=[mountain]
	"🏔", // snow-capped mountain, tags=[], aliases=[mountain_snow]
	"🗻", // mount fuji, tags=[], aliases=[mount_fuji]
	"🌋", // volcano, tags=[], aliases=[volcano]
	"🏜", // desert, tags=[], aliases=[desert]
	"🏕", // camping, tags=[], aliases=[camping]
	"⛺️", // tent, tags=[camping], aliases=[tent]
	"🛤", // railway track, tags=[], aliases=[railway_track]
	"🛣", // motorway, tags=[], aliases=[motorway]
	"🏗", // building construction, tags=[], aliases=[building_construction]
	"🏭", // factory, tags=[], aliases=[factory]
	"🏠", // house, tags=[], aliases=[house]
	"🏡", // house with garden, tags=[], aliases=[house_with_garden]
	"🏘", // house, tags=[], aliases=[houses]
	"🏚", // derelict house, tags=[], aliases=[derelict_house]
	"🏢", // office building, tags=[], aliases=[office]
	"🏬", // department store, tags=[], aliases=[department_store]
	"🏣", // Japanese post office, tags=[], aliases=[post_office]
	"🏤", // post office, tags=[], aliases=[european_post_office]
	"🏥", // hospital, tags=[], aliases=[hospital]
	"🏦", // bank, tags=[], aliases=[bank]
	"🏨", // hotel, tags=[], aliases=[hotel]
	"🏪", // convenience store, tags=[], aliases=[convenience_store]
	"🏫", // school, tags=[], aliases=[school]
	"🏩", // love hotel, tags=[], aliases=[love_hotel]
	"💒", // wedding, tags=[marriage], aliases=[wedding]
	"🏛", // classical building, tags=[], aliases=[classical_building]
	"⛪️", // church, tags=[], aliases=[church]
	"🕌", // mosque, tags=[], aliases=[mosque]
	"🕍", // synagogue, tags=[], aliases=[synagogue]
	"🕋", // kaaba, tags=[], aliases=[kaaba]
	"⛩", // shinto shrine, tags=[], aliases=[shinto_shrine]
	"🗾", // map of Japan, tags=[], aliases=[japan]
	"🎑", // moon viewing ceremony, tags=[], aliases=[rice_scene]
	"🏞", // national park, tags=[], aliases=[national_park]
	"🌅", // sunrise, tags=[], aliases=[sunrise]
	"🌄", // sunrise over mountains, tags=[], aliases=[sunrise_over_mountains]
	"🌠", // shooting star, tags=[], aliases=[stars]
	"🎇", // sparkler, tags=[], aliases=[sparkler]
	"🎆", // fireworks, tags=[festival celebration], aliases=[fireworks]
	"🌇", // sunset, tags=[], aliases=[city_sunrise]
	"🌆", // cityscape at dusk, tags=[], aliases=[city_sunset]
	"🏙", // cityscape, tags=[skyline], aliases=[cityscape]
	"🌃", // night with stars, tags=[], aliases=[night_with_stars]
	"🌌", // milky way, tags=[], aliases=[milky_way]
	"🌉", // bridge at night, tags=[], aliases=[bridge_at_night]
	"🌁", // foggy, tags=[karl], aliases=[foggy]
}
