package emojis

var CategoryNature = []string {
	"🐶", // dog face, tags=[pet], aliases=[dog]
	"🐱", // cat face, tags=[pet], aliases=[cat]
	"🐭", // mouse face, tags=[], aliases=[mouse]
	"🐹", // hamster face, tags=[pet], aliases=[hamster]
	"🐰", // rabbit face, tags=[bunny], aliases=[rabbit]
	"🦊", // fox face, tags=[], aliases=[fox_face]
	"🐻", // bear face, tags=[], aliases=[bear]
	"🐼", // panda face, tags=[], aliases=[panda_face]
	"🐨", // koala, tags=[], aliases=[koala]
	"🐯", // tiger face, tags=[], aliases=[tiger]
	"🦁", // lion face, tags=[], aliases=[lion]
	"🐮", // cow face, tags=[], aliases=[cow]
	"🐷", // pig face, tags=[], aliases=[pig]
	"🐽", // pig nose, tags=[], aliases=[pig_nose]
	"🐸", // frog face, tags=[], aliases=[frog]
	"🐵", // monkey face, tags=[], aliases=[monkey_face]
	"🙈", // see-no-evil monkey, tags=[monkey blind ignore], aliases=[see_no_evil]
	"🙉", // hear-no-evil monkey, tags=[monkey deaf], aliases=[hear_no_evil]
	"🙊", // speak-no-evil monkey, tags=[monkey mute hush], aliases=[speak_no_evil]
	"🐒", // monkey, tags=[], aliases=[monkey]
	"🐔", // chicken, tags=[], aliases=[chicken]
	"🐧", // penguin, tags=[], aliases=[penguin]
	"🐦", // bird, tags=[], aliases=[bird]
	"🐤", // baby chick, tags=[], aliases=[baby_chick]
	"🐣", // hatching chick, tags=[], aliases=[hatching_chick]
	"🐥", // front-facing baby chick, tags=[], aliases=[hatched_chick]
	"🦆", // duck, tags=[], aliases=[duck]
	"🦅", // eagle, tags=[], aliases=[eagle]
	"🦉", // owl, tags=[], aliases=[owl]
	"🦇", // bat, tags=[], aliases=[bat]
	"🐺", // wolf face, tags=[], aliases=[wolf]
	"🐗", // boar, tags=[], aliases=[boar]
	"🐴", // horse face, tags=[], aliases=[horse]
	"🦄", // unicorn face, tags=[], aliases=[unicorn]
	"🐝", // honeybee, tags=[], aliases=[bee honeybee]
	"🐛", // bug, tags=[], aliases=[bug]
	"🦋", // butterfly, tags=[], aliases=[butterfly]
	"🐌", // snail, tags=[slow], aliases=[snail]
	"🐚", // spiral shell, tags=[sea beach], aliases=[shell]
	"🐞", // lady beetle, tags=[bug], aliases=[beetle]
	"🐜", // ant, tags=[], aliases=[ant]
	"🕷", // spider, tags=[], aliases=[spider]
	"🕸", // spider web, tags=[], aliases=[spider_web]
	"🐢", // turtle, tags=[slow], aliases=[turtle]
	"🐍", // snake, tags=[], aliases=[snake]
	"🦎", // lizard, tags=[], aliases=[lizard]
	"🦂", // scorpion, tags=[], aliases=[scorpion]
	"🦀", // crab, tags=[], aliases=[crab]
	"🦑", // squid, tags=[], aliases=[squid]
	"🐙", // octopus, tags=[], aliases=[octopus]
	"🦐", // shrimp, tags=[], aliases=[shrimp]
	"🐠", // tropical fish, tags=[], aliases=[tropical_fish]
	"🐟", // fish, tags=[], aliases=[fish]
	"🐡", // blowfish, tags=[], aliases=[blowfish]
	"🐬", // dolphin, tags=[], aliases=[dolphin flipper]
	"🦈", // shark, tags=[], aliases=[shark]
	"🐳", // spouting whale, tags=[sea], aliases=[whale]
	"🐋", // whale, tags=[], aliases=[whale2]
	"🐊", // crocodile, tags=[], aliases=[crocodile]
	"🐆", // leopard, tags=[], aliases=[leopard]
	"🐅", // tiger, tags=[], aliases=[tiger2]
	"🐃", // water buffalo, tags=[], aliases=[water_buffalo]
	"🐂", // ox, tags=[], aliases=[ox]
	"🐄", // cow, tags=[], aliases=[cow2]
	"🦌", // deer, tags=[], aliases=[deer]
	"🐪", // camel, tags=[desert], aliases=[dromedary_camel]
	"🐫", // two-hump camel, tags=[], aliases=[camel]
	"🐘", // elephant, tags=[], aliases=[elephant]
	"🦏", // rhinoceros, tags=[], aliases=[rhinoceros]
	"🦍", // gorilla, tags=[], aliases=[gorilla]
	"🐎", // horse, tags=[speed], aliases=[racehorse]
	"🐖", // pig, tags=[], aliases=[pig2]
	"🐐", // goat, tags=[], aliases=[goat]
	"🐏", // ram, tags=[], aliases=[ram]
	"🐑", // sheep, tags=[], aliases=[sheep]
	"🐕", // dog, tags=[], aliases=[dog2]
	"🐩", // poodle, tags=[dog], aliases=[poodle]
	"🐈", // cat, tags=[], aliases=[cat2]
	"🐓", // rooster, tags=[], aliases=[rooster]
	"🦃", // turkey, tags=[thanksgiving], aliases=[turkey]
	"🕊", // dove, tags=[peace], aliases=[dove]
	"🐇", // rabbit, tags=[], aliases=[rabbit2]
	"🐁", // mouse, tags=[], aliases=[mouse2]
	"🐀", // rat, tags=[], aliases=[rat]
	"🐿", // chipmunk, tags=[], aliases=[chipmunk]
	"🐾", // paw prints, tags=[], aliases=[feet paw_prints]
	"🐉", // dragon, tags=[], aliases=[dragon]
	"🐲", // dragon face, tags=[], aliases=[dragon_face]
	"🌵", // cactus, tags=[], aliases=[cactus]
	"🎄", // Christmas tree, tags=[], aliases=[christmas_tree]
	"🌲", // evergreen tree, tags=[wood], aliases=[evergreen_tree]
	"🌳", // deciduous tree, tags=[wood], aliases=[deciduous_tree]
	"🌴", // palm tree, tags=[], aliases=[palm_tree]
	"🌱", // seedling, tags=[plant], aliases=[seedling]
	"🌿", // herb, tags=[], aliases=[herb]
	"☘️", // shamrock, tags=[], aliases=[shamrock]
	"🍀", // four leaf clover, tags=[luck], aliases=[four_leaf_clover]
	"🎍", // pine decoration, tags=[], aliases=[bamboo]
	"🎋", // tanabata tree, tags=[], aliases=[tanabata_tree]
	"🍃", // leaf fluttering in wind, tags=[leaf], aliases=[leaves]
	"🍂", // fallen leaf, tags=[autumn], aliases=[fallen_leaf]
	"🍁", // maple leaf, tags=[canada], aliases=[maple_leaf]
	"🍄", // mushroom, tags=[], aliases=[mushroom]
	"🌾", // sheaf of rice, tags=[], aliases=[ear_of_rice]
	"💐", // bouquet, tags=[flowers], aliases=[bouquet]
	"🌷", // tulip, tags=[flower], aliases=[tulip]
	"🌹", // rose, tags=[flower], aliases=[rose]
	"🥀", // wilted flower, tags=[], aliases=[wilted_flower]
	"🌻", // sunflower, tags=[], aliases=[sunflower]
	"🌼", // blossom, tags=[], aliases=[blossom]
	"🌸", // cherry blossom, tags=[flower spring], aliases=[cherry_blossom]
	"🌺", // hibiscus, tags=[], aliases=[hibiscus]
	"🌎", // globe showing Americas, tags=[globe world international], aliases=[earth_americas]
	"🌍", // globe showing Europe-Africa, tags=[globe world international], aliases=[earth_africa]
	"🌏", // globe showing Asia-Australia, tags=[globe world international], aliases=[earth_asia]
	"🌕", // full moon, tags=[], aliases=[full_moon]
	"🌖", // waning gibbous moon, tags=[], aliases=[waning_gibbous_moon]
	"🌗", // last quarter moon, tags=[], aliases=[last_quarter_moon]
	"🌘", // waning crescent moon, tags=[], aliases=[waning_crescent_moon]
	"🌑", // new moon, tags=[], aliases=[new_moon]
	"🌒", // waxing crescent moon, tags=[], aliases=[waxing_crescent_moon]
	"🌓", // first quarter moon, tags=[], aliases=[first_quarter_moon]
	"🌔", // waxing gibbous moon, tags=[], aliases=[moon waxing_gibbous_moon]
	"🌚", // new moon face, tags=[], aliases=[new_moon_with_face]
	"🌝", // full moon with face, tags=[], aliases=[full_moon_with_face]
	"🌞", // sun with face, tags=[summer], aliases=[sun_with_face]
	"🌛", // first quarter moon with face, tags=[], aliases=[first_quarter_moon_with_face]
	"🌜", // last quarter moon with face, tags=[], aliases=[last_quarter_moon_with_face]
	"🌙", // crescent moon, tags=[night], aliases=[crescent_moon]
	"💫", // dizzy, tags=[star], aliases=[dizzy]
	"⭐️", // white medium star, tags=[], aliases=[star]
	"🌟", // glowing star, tags=[], aliases=[star2]
	"✨", // sparkles, tags=[shiny], aliases=[sparkles]
	"⚡️", // high voltage, tags=[lightning thunder], aliases=[zap]
	"🔥", // fire, tags=[burn], aliases=[fire]
	"💥", // collision, tags=[explode], aliases=[boom collision]
	"☄", // comet, tags=[], aliases=[comet]
	"☀️", // sun, tags=[weather], aliases=[sunny]
	"🌤", // sun behind small cloud, tags=[], aliases=[sun_behind_small_cloud]
	"⛅️", // sun behind cloud, tags=[weather cloud], aliases=[partly_sunny]
	"🌥", // sun behind large cloud, tags=[], aliases=[sun_behind_large_cloud]
	"🌦", // sun behind rain cloud, tags=[], aliases=[sun_behind_rain_cloud]
	"🌈", // rainbow, tags=[], aliases=[rainbow]
	"☁️", // cloud, tags=[], aliases=[cloud]
	"🌧", // cloud with rain, tags=[], aliases=[cloud_with_rain]
	"⛈", // cloud with lightning and rain, tags=[], aliases=[cloud_with_lightning_and_rain]
	"🌩", // cloud with lightning, tags=[], aliases=[cloud_with_lightning]
	"🌨", // cloud with snow, tags=[], aliases=[cloud_with_snow]
	"☃️", // snowman, tags=[winter christmas], aliases=[snowman_with_snow]
	"⛄️", // snowman without snow, tags=[winter], aliases=[snowman]
	"❄️", // snowflake, tags=[winter cold weather], aliases=[snowflake]
	"🌬", // wind face, tags=[], aliases=[wind_face]
	"💨", // dashing away, tags=[wind blow fast], aliases=[dash]
	"🌪", // tornado, tags=[], aliases=[tornado]
	"🌫", // fog, tags=[], aliases=[fog]
	"🌊", // water wave, tags=[sea], aliases=[ocean]
	"💧", // droplet, tags=[water], aliases=[droplet]
	"💦", // sweat droplets, tags=[water workout], aliases=[sweat_drops]
	"☔️", // umbrella with rain drops, tags=[rain weather], aliases=[umbrella]
}
