package emoji

var CategoryFoods = []string {
	"🍏", // green apple, tags=[fruit], aliases=[green_apple]
	"🍎", // red apple, tags=[], aliases=[apple]
	"🍐", // pear, tags=[], aliases=[pear]
	"🍊", // tangerine, tags=[], aliases=[tangerine orange mandarin]
	"🍋", // lemon, tags=[], aliases=[lemon]
	"🍌", // banana, tags=[fruit], aliases=[banana]
	"🍉", // watermelon, tags=[], aliases=[watermelon]
	"🍇", // grapes, tags=[], aliases=[grapes]
	"🍓", // strawberry, tags=[fruit], aliases=[strawberry]
	"🍈", // melon, tags=[], aliases=[melon]
	"🍒", // cherries, tags=[fruit], aliases=[cherries]
	"🍑", // peach, tags=[], aliases=[peach]
	"🍍", // pineapple, tags=[], aliases=[pineapple]
	"🥝", // kiwi fruit, tags=[], aliases=[kiwi_fruit]
	"🥑", // avocado, tags=[], aliases=[avocado]
	"🍅", // tomato, tags=[], aliases=[tomato]
	"🍆", // eggplant, tags=[aubergine], aliases=[eggplant]
	"🥒", // cucumber, tags=[], aliases=[cucumber]
	"🥕", // carrot, tags=[], aliases=[carrot]
	"🌽", // ear of corn, tags=[], aliases=[corn]
	"🌶", // hot pepper, tags=[spicy], aliases=[hot_pepper]
	"🥔", // potato, tags=[], aliases=[potato]
	"🍠", // roasted sweet potato, tags=[], aliases=[sweet_potato]
	"🌰", // chestnut, tags=[], aliases=[chestnut]
	"🥜", // peanuts, tags=[], aliases=[peanuts]
	"🍯", // honey pot, tags=[], aliases=[honey_pot]
	"🥐", // croissant, tags=[], aliases=[croissant]
	"🍞", // bread, tags=[toast], aliases=[bread]
	"🥖", // baguette bread, tags=[], aliases=[baguette_bread]
	"🧀", // cheese wedge, tags=[], aliases=[cheese]
	"🥚", // egg, tags=[], aliases=[egg]
	"🍳", // cooking, tags=[breakfast], aliases=[fried_egg]
	"🥓", // bacon, tags=[], aliases=[bacon]
	"🥞", // pancakes, tags=[], aliases=[pancakes]
	"🍤", // fried shrimp, tags=[tempura], aliases=[fried_shrimp]
	"🍗", // poultry leg, tags=[meat chicken], aliases=[poultry_leg]
	"🍖", // meat on bone, tags=[], aliases=[meat_on_bone]
	"🍕", // pizza, tags=[], aliases=[pizza]
	"🌭", // hot dog, tags=[], aliases=[hotdog]
	"🍔", // hamburger, tags=[burger], aliases=[hamburger]
	"🍟", // french fries, tags=[], aliases=[fries]
	"🥙", // stuffed flatbread, tags=[], aliases=[stuffed_flatbread]
	"🌮", // taco, tags=[], aliases=[taco]
	"🌯", // burrito, tags=[], aliases=[burrito]
	"🥗", // green salad, tags=[], aliases=[green_salad]
	"🥘", // shallow pan of food, tags=[paella curry], aliases=[shallow_pan_of_food]
	"🍝", // spaghetti, tags=[pasta], aliases=[spaghetti]
	"🍜", // steaming bowl, tags=[noodle], aliases=[ramen]
	"🍲", // pot of food, tags=[], aliases=[stew]
	"🍥", // fish cake with swirl, tags=[], aliases=[fish_cake]
	"🍣", // sushi, tags=[], aliases=[sushi]
	"🍱", // bento box, tags=[], aliases=[bento]
	"🍛", // curry rice, tags=[], aliases=[curry]
	"🍚", // cooked rice, tags=[], aliases=[rice]
	"🍙", // rice ball, tags=[], aliases=[rice_ball]
	"🍘", // rice cracker, tags=[], aliases=[rice_cracker]
	"🍢", // oden, tags=[], aliases=[oden]
	"🍡", // dango, tags=[], aliases=[dango]
	"🍧", // shaved ice, tags=[], aliases=[shaved_ice]
	"🍨", // ice cream, tags=[], aliases=[ice_cream]
	"🍦", // soft ice cream, tags=[], aliases=[icecream]
	"🍰", // shortcake, tags=[dessert], aliases=[cake]
	"🎂", // birthday cake, tags=[party], aliases=[birthday]
	"🍮", // custard, tags=[], aliases=[custard]
	"🍭", // lollipop, tags=[], aliases=[lollipop]
	"🍬", // candy, tags=[sweet], aliases=[candy]
	"🍫", // chocolate bar, tags=[], aliases=[chocolate_bar]
	"🍿", // popcorn, tags=[], aliases=[popcorn]
	"🍩", // doughnut, tags=[], aliases=[doughnut]
	"🍪", // cookie, tags=[], aliases=[cookie]
	"🥛", // glass of milk, tags=[], aliases=[milk_glass]
	"🍼", // baby bottle, tags=[milk], aliases=[baby_bottle]
	"☕️", // hot beverage, tags=[cafe espresso], aliases=[coffee]
	"🍵", // teacup without handle, tags=[green breakfast], aliases=[tea]
	"🍶", // sake, tags=[], aliases=[sake]
	"🍺", // beer mug, tags=[drink], aliases=[beer]
	"🍻", // clinking beer mugs, tags=[drinks], aliases=[beers]
	"🥂", // clinking glasses, tags=[cheers toast], aliases=[clinking_glasses]
	"🍷", // wine glass, tags=[], aliases=[wine_glass]
	"🥃", // tumbler glass, tags=[whisky], aliases=[tumbler_glass]
	"🍸", // cocktail glass, tags=[drink], aliases=[cocktail]
	"🍹", // tropical drink, tags=[summer vacation], aliases=[tropical_drink]
	"🍾", // bottle with popping cork, tags=[bottle bubbly celebration], aliases=[champagne]
	"🥄", // spoon, tags=[], aliases=[spoon]
	"🍴", // fork and knife, tags=[cutlery], aliases=[fork_and_knife]
	"🍽", // fork and knife with plate, tags=[dining dinner], aliases=[plate_with_cutlery]
}
