package emoji

var CategorySymbols = []string {
	"❤️", // red heart, tags=[love], aliases=[heart]
	"💛", // yellow heart, tags=[], aliases=[yellow_heart]
	"💚", // green heart, tags=[], aliases=[green_heart]
	"💙", // blue heart, tags=[], aliases=[blue_heart]
	"💜", // purple heart, tags=[], aliases=[purple_heart]
	"🖤", // black heart, tags=[], aliases=[black_heart]
	"💔", // broken heart, tags=[], aliases=[broken_heart]
	"❣️", // heavy heart exclamation, tags=[], aliases=[heavy_heart_exclamation]
	"💕", // two hearts, tags=[], aliases=[two_hearts]
	"💞", // revolving hearts, tags=[], aliases=[revolving_hearts]
	"💓", // beating heart, tags=[], aliases=[heartbeat]
	"💗", // growing heart, tags=[], aliases=[heartpulse]
	"💖", // sparkling heart, tags=[], aliases=[sparkling_heart]
	"💘", // heart with arrow, tags=[love heart], aliases=[cupid]
	"💝", // heart with ribbon, tags=[chocolates], aliases=[gift_heart]
	"💟", // heart decoration, tags=[], aliases=[heart_decoration]
	"☮️", // peace symbol, tags=[], aliases=[peace_symbol]
	"✝️", // latin cross, tags=[], aliases=[latin_cross]
	"☪️", // star and crescent, tags=[], aliases=[star_and_crescent]
	"🕉", // om, tags=[], aliases=[om]
	"☸️", // wheel of dharma, tags=[], aliases=[wheel_of_dharma]
	"✡️", // star of David, tags=[], aliases=[star_of_david]
	"🔯", // dotted six-pointed star, tags=[], aliases=[six_pointed_star]
	"🕎", // menorah, tags=[], aliases=[menorah]
	"☯️", // yin yang, tags=[], aliases=[yin_yang]
	"☦️", // orthodox cross, tags=[], aliases=[orthodox_cross]
	"🛐", // place of worship, tags=[], aliases=[place_of_worship]
	"⛎", // Ophiuchus, tags=[], aliases=[ophiuchus]
	"♈️", // Aries, tags=[], aliases=[aries]
	"♉️", // Taurus, tags=[], aliases=[taurus]
	"♊️", // Gemini, tags=[], aliases=[gemini]
	"♋️", // Cancer, tags=[], aliases=[cancer]
	"♌️", // Leo, tags=[], aliases=[leo]
	"♍️", // Virgo, tags=[], aliases=[virgo]
	"♎️", // Libra, tags=[], aliases=[libra]
	"♏️", // Scorpius, tags=[], aliases=[scorpius]
	"♐️", // Sagittarius, tags=[], aliases=[sagittarius]
	"♑️", // Capricorn, tags=[], aliases=[capricorn]
	"♒️", // Aquarius, tags=[], aliases=[aquarius]
	"♓️", // Pisces, tags=[], aliases=[pisces]
	"🆔", // ID button, tags=[], aliases=[id]
	"⚛️", // atom symbol, tags=[], aliases=[atom_symbol]
	"🉑", // Japanese “acceptable” button, tags=[], aliases=[accept]
	"☢️", // radioactive, tags=[], aliases=[radioactive]
	"☣️", // biohazard, tags=[], aliases=[biohazard]
	"📴", // mobile phone off, tags=[mute off], aliases=[mobile_phone_off]
	"📳", // vibration mode, tags=[], aliases=[vibration_mode]
	"🈶", // Japanese “not free of charge” button, tags=[], aliases=[u6709]
	"🈚️", // Japanese “free of charge” button, tags=[], aliases=[u7121]
	"🈸", // Japanese “application” button, tags=[], aliases=[u7533]
	"🈺", // Japanese “open for business” button, tags=[], aliases=[u55b6]
	"🈷️", // Japanese “monthly amount” button, tags=[], aliases=[u6708]
	"✴️", // eight-pointed star, tags=[], aliases=[eight_pointed_black_star]
	"🆚", // VS button, tags=[], aliases=[vs]
	"💮", // white flower, tags=[], aliases=[white_flower]
	"🉐", // Japanese “bargain” button, tags=[], aliases=[ideograph_advantage]
	"㊙️", // Japanese “secret” button, tags=[], aliases=[secret]
	"㊗️", // Japanese “congratulations” button, tags=[], aliases=[congratulations]
	"🈴", // Japanese “passing grade” button, tags=[], aliases=[u5408]
	"🈵", // Japanese “no vacancy” button, tags=[], aliases=[u6e80]
	"🈹", // Japanese “discount” button, tags=[], aliases=[u5272]
	"🈲", // Japanese “prohibited” button, tags=[], aliases=[u7981]
	"🅰️", // A button (blood type), tags=[], aliases=[a]
	"🅱️", // B button (blood type), tags=[], aliases=[b]
	"🆎", // AB button (blood type), tags=[], aliases=[ab]
	"🆑", // CL button, tags=[], aliases=[cl]
	"🅾️", // O button (blood type), tags=[], aliases=[o2]
	"🆘", // SOS button, tags=[help emergency], aliases=[sos]
	"❌", // cross mark, tags=[], aliases=[x]
	"⭕️", // heavy large circle, tags=[], aliases=[o]
	"🛑", // stop sign, tags=[], aliases=[stop_sign]
	"⛔️", // no entry, tags=[limit], aliases=[no_entry]
	"📛", // name badge, tags=[], aliases=[name_badge]
	"🚫", // prohibited, tags=[block forbidden], aliases=[no_entry_sign]
	"💯", // hundred points, tags=[score perfect], aliases=[100]
	"💢", // anger symbol, tags=[angry], aliases=[anger]
	"♨️", // hot springs, tags=[], aliases=[hotsprings]
	"🚷", // no pedestrians, tags=[], aliases=[no_pedestrians]
	"🚯", // no littering, tags=[], aliases=[do_not_litter]
	"🚳", // no bicycles, tags=[], aliases=[no_bicycles]
	"🚱", // non-potable water, tags=[], aliases=[non-potable_water]
	"🔞", // no one under eighteen, tags=[], aliases=[underage]
	"📵", // no mobile phones, tags=[], aliases=[no_mobile_phones]
	"🚭", // no smoking, tags=[], aliases=[no_smoking]
	"❗️", // exclamation mark, tags=[bang], aliases=[exclamation heavy_exclamation_mark]
	"❕", // white exclamation mark, tags=[], aliases=[grey_exclamation]
	"❓", // question mark, tags=[confused], aliases=[question]
	"❔", // white question mark, tags=[], aliases=[grey_question]
	"‼️", // double exclamation mark, tags=[], aliases=[bangbang]
	"⁉️", // exclamation question mark, tags=[], aliases=[interrobang]
	"🔅", // dim button, tags=[], aliases=[low_brightness]
	"🔆", // bright button, tags=[], aliases=[high_brightness]
	"〽️", // part alternation mark, tags=[], aliases=[part_alternation_mark]
	"⚠️", // warning, tags=[wip], aliases=[warning]
	"🚸", // children crossing, tags=[], aliases=[children_crossing]
	"🔱", // trident emblem, tags=[], aliases=[trident]
	"⚜️", // fleur-de-lis, tags=[], aliases=[fleur_de_lis]
	"🔰", // Japanese symbol for beginner, tags=[], aliases=[beginner]
	"♻️", // recycling symbol, tags=[environment green], aliases=[recycle]
	"✅", // white heavy check mark, tags=[], aliases=[white_check_mark]
	"🈯️", // Japanese “reserved” button, tags=[], aliases=[u6307]
	"💹", // chart increasing with yen, tags=[], aliases=[chart]
	"❇️", // sparkle, tags=[], aliases=[sparkle]
	"✳️", // eight-spoked asterisk, tags=[], aliases=[eight_spoked_asterisk]
	"❎", // cross mark button, tags=[], aliases=[negative_squared_cross_mark]
	"🌐", // globe with meridians, tags=[world global international], aliases=[globe_with_meridians]
	"💠", // diamond with a dot, tags=[], aliases=[diamond_shape_with_a_dot_inside]
	"Ⓜ️", // circled M, tags=[], aliases=[m]
	"🌀", // cyclone, tags=[swirl], aliases=[cyclone]
	"💤", // zzz, tags=[sleeping], aliases=[zzz]
	"🏧", // ATM sign, tags=[], aliases=[atm]
	"🚾", // water closet, tags=[toilet restroom], aliases=[wc]
	"♿️", // wheelchair symbol, tags=[accessibility], aliases=[wheelchair]
	"🅿️", // P button, tags=[], aliases=[parking]
	"🈳", // Japanese “vacancy” button, tags=[], aliases=[u7a7a]
	"🈂️", // Japanese “service charge” button, tags=[], aliases=[sa]
	"🛂", // passport control, tags=[], aliases=[passport_control]
	"🛃", // customs, tags=[], aliases=[customs]
	"🛄", // baggage claim, tags=[airport], aliases=[baggage_claim]
	"🛅", // left luggage, tags=[], aliases=[left_luggage]
	"🚹", // men’s room, tags=[], aliases=[mens]
	"🚺", // women’s room, tags=[], aliases=[womens]
	"🚼", // baby symbol, tags=[], aliases=[baby_symbol]
	"🚻", // restroom, tags=[toilet], aliases=[restroom]
	"🚮", // litter in bin sign, tags=[], aliases=[put_litter_in_its_place]
	"🎦", // cinema, tags=[film movie], aliases=[cinema]
	"📶", // antenna bars, tags=[wifi], aliases=[signal_strength]
	"🈁", // Japanese “here” button, tags=[], aliases=[koko]
	"🔣", // input symbols, tags=[], aliases=[symbols]
	"ℹ️", // information, tags=[], aliases=[information_source]
	"🔤", // input latin letters, tags=[alphabet], aliases=[abc]
	"🔡", // input latin lowercase, tags=[], aliases=[abcd]
	"🔠", // input latin uppercase, tags=[letters], aliases=[capital_abcd]
	"🆖", // NG button, tags=[], aliases=[ng]
	"🆗", // OK button, tags=[yes], aliases=[ok]
	"🆙", // UP! button, tags=[], aliases=[up]
	"🆒", // COOL button, tags=[], aliases=[cool]
	"🆕", // NEW button, tags=[fresh], aliases=[new]
	"🆓", // FREE button, tags=[], aliases=[free]
	"0️⃣", // keycap: 0, tags=[], aliases=[zero]
	"1️⃣", // keycap: 1, tags=[], aliases=[one]
	"2️⃣", // keycap: 2, tags=[], aliases=[two]
	"3️⃣", // keycap: 3, tags=[], aliases=[three]
	"4️⃣", // keycap: 4, tags=[], aliases=[four]
	"5️⃣", // keycap: 5, tags=[], aliases=[five]
	"6️⃣", // keycap: 6, tags=[], aliases=[six]
	"7️⃣", // keycap: 7, tags=[], aliases=[seven]
	"8️⃣", // keycap: 8, tags=[], aliases=[eight]
	"9️⃣", // keycap: 9, tags=[], aliases=[nine]
	"🔟", // keycap 10, tags=[], aliases=[keycap_ten]
	"🔢", // input numbers, tags=[numbers], aliases=[1234]
	"#️⃣", // keycap: #, tags=[number], aliases=[hash]
	"*️⃣", // keycap: *, tags=[], aliases=[asterisk]
	"▶️", // play button, tags=[], aliases=[arrow_forward]
	"⏸", // pause button, tags=[], aliases=[pause_button]
	"⏯", // play or pause button, tags=[], aliases=[play_or_pause_button]
	"⏹", // stop button, tags=[], aliases=[stop_button]
	"⏺", // record button, tags=[], aliases=[record_button]
	"⏭", // next track button, tags=[], aliases=[next_track_button]
	"⏮", // last track button, tags=[], aliases=[previous_track_button]
	"⏩", // fast-forward button, tags=[], aliases=[fast_forward]
	"⏪", // fast reverse button, tags=[], aliases=[rewind]
	"⏫", // fast up button, tags=[], aliases=[arrow_double_up]
	"⏬", // fast down button, tags=[], aliases=[arrow_double_down]
	"◀️", // reverse button, tags=[], aliases=[arrow_backward]
	"🔼", // up button, tags=[], aliases=[arrow_up_small]
	"🔽", // down button, tags=[], aliases=[arrow_down_small]
	"➡️", // right arrow, tags=[], aliases=[arrow_right]
	"⬅️", // left arrow, tags=[], aliases=[arrow_left]
	"⬆️", // up arrow, tags=[], aliases=[arrow_up]
	"⬇️", // down arrow, tags=[], aliases=[arrow_down]
	"↗️", // up-right arrow, tags=[], aliases=[arrow_upper_right]
	"↘️", // down-right arrow, tags=[], aliases=[arrow_lower_right]
	"↙️", // down-left arrow, tags=[], aliases=[arrow_lower_left]
	"↖️", // up-left arrow, tags=[], aliases=[arrow_upper_left]
	"↕️", // up-down arrow, tags=[], aliases=[arrow_up_down]
	"↔️", // left-right arrow, tags=[], aliases=[left_right_arrow]
	"↪️", // left arrow curving right, tags=[], aliases=[arrow_right_hook]
	"↩️", // right arrow curving left, tags=[return], aliases=[leftwards_arrow_with_hook]
	"⤴️", // right arrow curving up, tags=[], aliases=[arrow_heading_up]
	"⤵️", // right arrow curving down, tags=[], aliases=[arrow_heading_down]
	"🔀", // shuffle tracks button, tags=[shuffle], aliases=[twisted_rightwards_arrows]
	"🔁", // repeat button, tags=[loop], aliases=[repeat]
	"🔂", // repeat single button, tags=[], aliases=[repeat_one]
	"🔄", // anticlockwise arrows button, tags=[sync], aliases=[arrows_counterclockwise]
	"🔃", // clockwise vertical arrows, tags=[], aliases=[arrows_clockwise]
	"🎵", // musical note, tags=[], aliases=[musical_note]
	"🎶", // musical notes, tags=[music], aliases=[notes]
	"➕", // heavy plus sign, tags=[], aliases=[heavy_plus_sign]
	"➖", // heavy minus sign, tags=[], aliases=[heavy_minus_sign]
	"➗", // heavy division sign, tags=[], aliases=[heavy_division_sign]
	"✖️", // heavy multiplication x, tags=[], aliases=[heavy_multiplication_x]
	"💲", // heavy dollar sign, tags=[], aliases=[heavy_dollar_sign]
	"💱", // currency exchange, tags=[], aliases=[currency_exchange]
	"™️", // trade mark, tags=[trademark], aliases=[tm]
	"©️", // copyright, tags=[], aliases=[copyright]
	"®️", // registered, tags=[], aliases=[registered]
	"〰️", // wavy dash, tags=[], aliases=[wavy_dash]
	"➰", // curly loop, tags=[], aliases=[curly_loop]
	"➿", // double curly loop, tags=[], aliases=[loop]
	"🔚", // END arrow, tags=[], aliases=[end]
	"🔙", // BACK arrow, tags=[], aliases=[back]
	"🔛", // ON! arrow, tags=[], aliases=[on]
	"🔝", // TOP arrow, tags=[], aliases=[top]
	"🔜", // SOON arrow, tags=[], aliases=[soon]
	"✔️", // heavy check mark, tags=[], aliases=[heavy_check_mark]
	"☑️", // ballot box with check, tags=[], aliases=[ballot_box_with_check]
	"🔘", // radio button, tags=[], aliases=[radio_button]
	"⚪️", // white circle, tags=[], aliases=[white_circle]
	"⚫️", // black circle, tags=[], aliases=[black_circle]
	"🔴", // red circle, tags=[], aliases=[red_circle]
	"🔵", // blue circle, tags=[], aliases=[large_blue_circle]
	"🔺", // red triangle pointed up, tags=[], aliases=[small_red_triangle]
	"🔻", // red triangle pointed down, tags=[], aliases=[small_red_triangle_down]
	"🔸", // small orange diamond, tags=[], aliases=[small_orange_diamond]
	"🔹", // small blue diamond, tags=[], aliases=[small_blue_diamond]
	"🔶", // large orange diamond, tags=[], aliases=[large_orange_diamond]
	"🔷", // large blue diamond, tags=[], aliases=[large_blue_diamond]
	"🔳", // white square button, tags=[], aliases=[white_square_button]
	"🔲", // black square button, tags=[], aliases=[black_square_button]
	"▪️", // black small square, tags=[], aliases=[black_small_square]
	"▫️", // white small square, tags=[], aliases=[white_small_square]
	"◾️", // black medium-small square, tags=[], aliases=[black_medium_small_square]
	"◽️", // white medium-small square, tags=[], aliases=[white_medium_small_square]
	"◼️", // black medium square, tags=[], aliases=[black_medium_square]
	"◻️", // white medium square, tags=[], aliases=[white_medium_square]
	"⬛️", // black large square, tags=[], aliases=[black_large_square]
	"⬜️", // white large square, tags=[], aliases=[white_large_square]
	"🔈", // speaker low volume, tags=[], aliases=[speaker]
	"🔇", // muted speaker, tags=[sound volume], aliases=[mute]
	"🔉", // speaker medium volume, tags=[volume], aliases=[sound]
	"🔊", // speaker high volume, tags=[volume], aliases=[loud_sound]
	"🔔", // bell, tags=[sound notification], aliases=[bell]
	"🔕", // bell with slash, tags=[volume off], aliases=[no_bell]
	"📣", // megaphone, tags=[], aliases=[mega]
	"📢", // loudspeaker, tags=[announcement], aliases=[loudspeaker]
	"👁‍🗨", // eye in speech bubble, tags=[], aliases=[eye_speech_bubble]
	"💬", // speech balloon, tags=[comment], aliases=[speech_balloon]
	"💭", // thought balloon, tags=[thinking], aliases=[thought_balloon]
	"🗯", // right anger bubble, tags=[], aliases=[right_anger_bubble]
	"♠️", // spade suit, tags=[], aliases=[spades]
	"♣️", // club suit, tags=[], aliases=[clubs]
	"♥️", // heart suit, tags=[], aliases=[hearts]
	"♦️", // diamond suit, tags=[], aliases=[diamonds]
	"🃏", // joker, tags=[], aliases=[black_joker]
	"🎴", // flower playing cards, tags=[], aliases=[flower_playing_cards]
	"🀄️", // mahjong red dragon, tags=[], aliases=[mahjong]
	"🕐", // one o’clock, tags=[], aliases=[clock1]
	"🕑", // two o’clock, tags=[], aliases=[clock2]
	"🕒", // three o’clock, tags=[], aliases=[clock3]
	"🕓", // four o’clock, tags=[], aliases=[clock4]
	"🕔", // five o’clock, tags=[], aliases=[clock5]
	"🕕", // six o’clock, tags=[], aliases=[clock6]
	"🕖", // seven o’clock, tags=[], aliases=[clock7]
	"🕗", // eight o’clock, tags=[], aliases=[clock8]
	"🕘", // nine o’clock, tags=[], aliases=[clock9]
	"🕙", // ten o’clock, tags=[], aliases=[clock10]
	"🕚", // eleven o’clock, tags=[], aliases=[clock11]
	"🕛", // twelve o’clock, tags=[], aliases=[clock12]
	"🕜", // one-thirty, tags=[], aliases=[clock130]
	"🕝", // two-thirty, tags=[], aliases=[clock230]
	"🕞", // three-thirty, tags=[], aliases=[clock330]
	"🕟", // four-thirty, tags=[], aliases=[clock430]
	"🕠", // five-thirty, tags=[], aliases=[clock530]
	"🕡", // six-thirty, tags=[], aliases=[clock630]
	"🕢", // seven-thirty, tags=[], aliases=[clock730]
	"🕣", // eight-thirty, tags=[], aliases=[clock830]
	"🕤", // nine-thirty, tags=[], aliases=[clock930]
	"🕥", // ten-thirty, tags=[], aliases=[clock1030]
	"🕦", // eleven-thirty, tags=[], aliases=[clock1130]
	"🕧", // twelve-thirty, tags=[], aliases=[clock1230]
}
