package emoji

var CategoryPeople = []string {
	"😀", // grinning face, tags=[smile happy], aliases=[grinning]
	"😃", // smiling face with open mouth, tags=[happy joy haha], aliases=[smiley]
	"😄", // smiling face with open mouth & smiling eyes, tags=[happy joy laugh pleased], aliases=[smile]
	"😁", // grinning face with smiling eyes, tags=[], aliases=[grin]
	"😆", // smiling face with open mouth & closed eyes, tags=[happy haha], aliases=[laughing satisfied]
	"😅", // smiling face with open mouth & cold sweat, tags=[hot], aliases=[sweat_smile]
	"😂", // face with tears of joy, tags=[tears], aliases=[joy]
	"🤣", // rolling on the floor laughing, tags=[lol laughing], aliases=[rofl]
	"☺️", // smiling face, tags=[blush pleased], aliases=[relaxed]
	"😊", // smiling face with smiling eyes, tags=[proud], aliases=[blush]
	"😇", // smiling face with halo, tags=[angel], aliases=[innocent]
	"🙂", // slightly smiling face, tags=[], aliases=[slightly_smiling_face]
	"🙃", // upside-down face, tags=[], aliases=[upside_down_face]
	"😉", // winking face, tags=[flirt], aliases=[wink]
	"😌", // relieved face, tags=[whew], aliases=[relieved]
	"😍", // smiling face with heart-eyes, tags=[love crush], aliases=[heart_eyes]
	"😘", // face blowing a kiss, tags=[flirt], aliases=[kissing_heart]
	"😗", // kissing face, tags=[], aliases=[kissing]
	"😙", // kissing face with smiling eyes, tags=[], aliases=[kissing_smiling_eyes]
	"😚", // kissing face with closed eyes, tags=[], aliases=[kissing_closed_eyes]
	"😋", // face savouring delicious food, tags=[tongue lick], aliases=[yum]
	"😜", // face with stuck-out tongue & winking eye, tags=[prank silly], aliases=[stuck_out_tongue_winking_eye]
	"😝", // face with stuck-out tongue & closed eyes, tags=[prank], aliases=[stuck_out_tongue_closed_eyes]
	"😛", // face with stuck-out tongue, tags=[], aliases=[stuck_out_tongue]
	"🤑", // money-mouth face, tags=[rich], aliases=[money_mouth_face]
	"🤗", // hugging face, tags=[], aliases=[hugs]
	"🤓", // nerd face, tags=[geek glasses], aliases=[nerd_face]
	"😎", // smiling face with sunglasses, tags=[cool], aliases=[sunglasses]
	"🤡", // clown face, tags=[], aliases=[clown_face]
	"🤠", // cowboy hat face, tags=[], aliases=[cowboy_hat_face]
	"😏", // smirking face, tags=[smug], aliases=[smirk]
	"😒", // unamused face, tags=[meh], aliases=[unamused]
	"😞", // disappointed face, tags=[sad], aliases=[disappointed]
	"😔", // pensive face, tags=[], aliases=[pensive]
	"😟", // worried face, tags=[nervous], aliases=[worried]
	"😕", // confused face, tags=[], aliases=[confused]
	"🙁", // slightly frowning face, tags=[], aliases=[slightly_frowning_face]
	"☹️", // frowning face, tags=[], aliases=[frowning_face]
	"😣", // persevering face, tags=[struggling], aliases=[persevere]
	"😖", // confounded face, tags=[], aliases=[confounded]
	"😫", // tired face, tags=[upset whine], aliases=[tired_face]
	"😩", // weary face, tags=[tired], aliases=[weary]
	"😤", // face with steam from nose, tags=[smug], aliases=[triumph]
	"😠", // angry face, tags=[mad annoyed], aliases=[angry]
	"😡", // pouting face, tags=[angry], aliases=[rage pout]
	"😶", // face without mouth, tags=[mute silence], aliases=[no_mouth]
	"😐", // neutral face, tags=[meh], aliases=[neutral_face]
	"😑", // expressionless face, tags=[], aliases=[expressionless]
	"😯", // hushed face, tags=[silence speechless], aliases=[hushed]
	"😦", // frowning face with open mouth, tags=[], aliases=[frowning]
	"😧", // anguished face, tags=[stunned], aliases=[anguished]
	"😮", // face with open mouth, tags=[surprise impressed wow], aliases=[open_mouth]
	"😲", // astonished face, tags=[amazed gasp], aliases=[astonished]
	"😵", // dizzy face, tags=[], aliases=[dizzy_face]
	"😳", // flushed face, tags=[], aliases=[flushed]
	"😱", // face screaming in fear, tags=[horror shocked], aliases=[scream]
	"😨", // fearful face, tags=[scared shocked oops], aliases=[fearful]
	"😰", // face with open mouth & cold sweat, tags=[nervous], aliases=[cold_sweat]
	"😢", // crying face, tags=[sad tear], aliases=[cry]
	"😥", // disappointed but relieved face, tags=[phew sweat nervous], aliases=[disappointed_relieved]
	"🤤", // drooling face, tags=[], aliases=[drooling_face]
	"😭", // loudly crying face, tags=[sad cry bawling], aliases=[sob]
	"😓", // face with cold sweat, tags=[], aliases=[sweat]
	"😪", // sleepy face, tags=[tired], aliases=[sleepy]
	"😴", // sleeping face, tags=[zzz], aliases=[sleeping]
	"🙄", // face with rolling eyes, tags=[], aliases=[roll_eyes]
	"🤔", // thinking face, tags=[], aliases=[thinking]
	"🤥", // lying face, tags=[liar], aliases=[lying_face]
	"😬", // grimacing face, tags=[], aliases=[grimacing]
	"🤐", // zipper-mouth face, tags=[silence hush], aliases=[zipper_mouth_face]
	"🤢", // nauseated face, tags=[sick barf disgusted], aliases=[nauseated_face]
	"🤧", // sneezing face, tags=[achoo sick], aliases=[sneezing_face]
	"😷", // face with medical mask, tags=[sick ill], aliases=[mask]
	"🤒", // face with thermometer, tags=[sick], aliases=[face_with_thermometer]
	"🤕", // face with head-bandage, tags=[hurt], aliases=[face_with_head_bandage]
	"😈", // smiling face with horns, tags=[devil evil horns], aliases=[smiling_imp]
	"👿", // angry face with horns, tags=[angry devil evil horns], aliases=[imp]
	"👹", // ogre, tags=[monster], aliases=[japanese_ogre]
	"👺", // goblin, tags=[], aliases=[japanese_goblin]
	"💩", // pile of poo, tags=[crap], aliases=[hankey poop shit]
	"👻", // ghost, tags=[halloween], aliases=[ghost]
	"💀", // skull, tags=[dead danger poison], aliases=[skull]
	"☠️", // skull and crossbones, tags=[danger pirate], aliases=[skull_and_crossbones]
	"👽", // alien, tags=[ufo], aliases=[alien]
	"👾", // alien monster, tags=[game retro], aliases=[space_invader]
	"🤖", // robot face, tags=[], aliases=[robot]
	"🎃", // jack-o-lantern, tags=[halloween], aliases=[jack_o_lantern]
	"😺", // smiling cat face with open mouth, tags=[], aliases=[smiley_cat]
	"😸", // grinning cat face with smiling eyes, tags=[], aliases=[smile_cat]
	"😹", // cat face with tears of joy, tags=[], aliases=[joy_cat]
	"😻", // smiling cat face with heart-eyes, tags=[], aliases=[heart_eyes_cat]
	"😼", // cat face with wry smile, tags=[], aliases=[smirk_cat]
	"😽", // kissing cat face with closed eyes, tags=[], aliases=[kissing_cat]
	"🙀", // weary cat face, tags=[horror], aliases=[scream_cat]
	"😿", // crying cat face, tags=[sad tear], aliases=[crying_cat_face]
	"😾", // pouting cat face, tags=[], aliases=[pouting_cat]
	"👐", // open hands, tags=[], aliases=[open_hands]
	"🙌", // raising hands, tags=[hooray], aliases=[raised_hands]
	"👏", // clapping hands, tags=[praise applause], aliases=[clap]
	"🙏", // folded hands, tags=[please hope wish], aliases=[pray]
	"🤝", // handshake, tags=[deal], aliases=[handshake]
	"👍", // thumbs up, tags=[approve ok], aliases=[+1 thumbsup]
	"👎", // thumbs down, tags=[disapprove bury], aliases=[-1 thumbsdown]
	"👊", // oncoming fist, tags=[attack], aliases=[fist_oncoming facepunch punch]
	"✊", // raised fist, tags=[power], aliases=[fist_raised fist]
	"🤛", // left-facing fist, tags=[], aliases=[fist_left]
	"🤜", // right-facing fist, tags=[], aliases=[fist_right]
	"🤞", // crossed fingers, tags=[luck hopeful], aliases=[crossed_fingers]
	"✌️", // victory hand, tags=[victory peace], aliases=[v]
	"🤘", // sign of the horns, tags=[], aliases=[metal]
	"👌", // OK hand, tags=[], aliases=[ok_hand]
	"👈", // backhand index pointing left, tags=[], aliases=[point_left]
	"👉", // backhand index pointing right, tags=[], aliases=[point_right]
	"👆", // backhand index pointing up, tags=[], aliases=[point_up_2]
	"👇", // backhand index pointing down, tags=[], aliases=[point_down]
	"☝️", // index pointing up, tags=[], aliases=[point_up]
	"✋", // raised hand, tags=[highfive stop], aliases=[hand raised_hand]
	"🤚", // raised back of hand, tags=[], aliases=[raised_back_of_hand]
	"🖐", // raised hand with fingers splayed, tags=[], aliases=[raised_hand_with_fingers_splayed]
	"🖖", // vulcan salute, tags=[prosper spock], aliases=[vulcan_salute]
	"👋", // waving hand, tags=[goodbye], aliases=[wave]
	"🤙", // call me hand, tags=[], aliases=[call_me_hand]
	"💪", // flexed biceps, tags=[flex bicep strong workout], aliases=[muscle]
	"🖕", // middle finger, tags=[], aliases=[middle_finger fu]
	"✍️", // writing hand, tags=[], aliases=[writing_hand]
	"🤳", // selfie, tags=[], aliases=[selfie]
	"💅", // nail polish, tags=[beauty manicure], aliases=[nail_care]
	"💍", // ring, tags=[wedding marriage engaged], aliases=[ring]
	"💄", // lipstick, tags=[makeup], aliases=[lipstick]
	"💋", // kiss mark, tags=[lipstick], aliases=[kiss]
	"👄", // mouth, tags=[kiss], aliases=[lips]
	"👅", // tongue, tags=[taste], aliases=[tongue]
	"👂", // ear, tags=[hear sound listen], aliases=[ear]
	"👃", // nose, tags=[smell], aliases=[nose]
	"👣", // footprints, tags=[feet tracks], aliases=[footprints]
	"👁", // eye, tags=[], aliases=[eye]
	"👀", // eyes, tags=[look see watch], aliases=[eyes]
	"🗣", // speaking head, tags=[], aliases=[speaking_head]
	"👤", // bust in silhouette, tags=[user], aliases=[bust_in_silhouette]
	"👥", // busts in silhouette, tags=[users group team], aliases=[busts_in_silhouette]
	"👶", // baby, tags=[child newborn], aliases=[baby]
	"👦", // boy, tags=[child], aliases=[boy]
	"👧", // girl, tags=[child], aliases=[girl]
	"👨", // man, tags=[mustache father dad], aliases=[man]
	"👩", // woman, tags=[girls], aliases=[woman]
	"👱‍♀", // blond-haired woman, tags=[], aliases=[blonde_woman]
	"👱", // blond-haired person, tags=[boy], aliases=[blonde_man person_with_blond_hair]
	"👴", // old man, tags=[], aliases=[older_man]
	"👵", // old woman, tags=[], aliases=[older_woman]
	"👲", // man with Chinese cap, tags=[], aliases=[man_with_gua_pi_mao]
	"👳‍♀", // woman wearing turban, tags=[], aliases=[woman_with_turban]
	"👳", // person wearing turban, tags=[], aliases=[man_with_turban]
	"👮‍♀", // woman police officer, tags=[], aliases=[policewoman]
	"👮", // police officer, tags=[police law], aliases=[policeman cop]
	"👷‍♀", // woman construction worker, tags=[], aliases=[construction_worker_woman]
	"👷", // construction worker, tags=[helmet], aliases=[construction_worker_man construction_worker]
	"💂‍♀", // woman guard, tags=[], aliases=[guardswoman]
	"💂", // guard, tags=[], aliases=[guardsman]
	"🕵️‍♀️", // woman detective, tags=[sleuth], aliases=[female_detective]
	"🕵", // detective, tags=[sleuth], aliases=[male_detective detective]
	"👩‍⚕", // woman health worker, tags=[doctor nurse], aliases=[woman_health_worker]
	"👨‍⚕", // man health worker, tags=[doctor nurse], aliases=[man_health_worker]
	"👩‍🌾", // woman farmer, tags=[], aliases=[woman_farmer]
	"👨‍🌾", // man farmer, tags=[], aliases=[man_farmer]
	"👩‍🍳", // woman cook, tags=[chef], aliases=[woman_cook]
	"👨‍🍳", // man cook, tags=[chef], aliases=[man_cook]
	"👩‍🎓", // woman student, tags=[graduation], aliases=[woman_student]
	"👨‍🎓", // man student, tags=[graduation], aliases=[man_student]
	"👩‍🎤", // woman singer, tags=[rockstar], aliases=[woman_singer]
	"👨‍🎤", // man singer, tags=[rockstar], aliases=[man_singer]
	"👩‍🏫", // woman teacher, tags=[school professor], aliases=[woman_teacher]
	"👨‍🏫", // man teacher, tags=[school professor], aliases=[man_teacher]
	"👩‍🏭", // woman factory worker, tags=[], aliases=[woman_factory_worker]
	"👨‍🏭", // man factory worker, tags=[], aliases=[man_factory_worker]
	"👩‍💻", // woman technologist, tags=[coder], aliases=[woman_technologist]
	"👨‍💻", // man technologist, tags=[coder], aliases=[man_technologist]
	"👩‍💼", // woman office worker, tags=[business], aliases=[woman_office_worker]
	"👨‍💼", // man office worker, tags=[business], aliases=[man_office_worker]
	"👩‍🔧", // woman mechanic, tags=[], aliases=[woman_mechanic]
	"👨‍🔧", // man mechanic, tags=[], aliases=[man_mechanic]
	"👩‍🔬", // woman scientist, tags=[research], aliases=[woman_scientist]
	"👨‍🔬", // man scientist, tags=[research], aliases=[man_scientist]
	"👩‍🎨", // woman artist, tags=[painter], aliases=[woman_artist]
	"👨‍🎨", // man artist, tags=[painter], aliases=[man_artist]
	"👩‍🚒", // woman firefighter, tags=[], aliases=[woman_firefighter]
	"👨‍🚒", // man firefighter, tags=[], aliases=[man_firefighter]
	"👩‍✈", // woman pilot, tags=[], aliases=[woman_pilot]
	"👨‍✈", // man pilot, tags=[], aliases=[man_pilot]
	"👩‍🚀", // woman astronaut, tags=[space], aliases=[woman_astronaut]
	"👨‍🚀", // man astronaut, tags=[space], aliases=[man_astronaut]
	"👩‍⚖", // woman judge, tags=[justice], aliases=[woman_judge]
	"👨‍⚖", // man judge, tags=[justice], aliases=[man_judge]
	"🤶", // Mrs. Claus, tags=[santa], aliases=[mrs_claus]
	"🎅", // Santa Claus, tags=[christmas], aliases=[santa]
	"👸", // princess, tags=[blonde crown royal], aliases=[princess]
	"🤴", // prince, tags=[crown royal], aliases=[prince]
	"👰", // bride with veil, tags=[marriage wedding], aliases=[bride_with_veil]
	"🤵", // man in tuxedo, tags=[groom marriage wedding], aliases=[man_in_tuxedo]
	"👼", // baby angel, tags=[], aliases=[angel]
	"🤰", // pregnant woman, tags=[], aliases=[pregnant_woman]
	"🙇‍♀", // woman bowing, tags=[respect thanks], aliases=[bowing_woman]
	"🙇", // person bowing, tags=[respect thanks], aliases=[bowing_man bow]
	"💁", // person tipping hand, tags=[], aliases=[tipping_hand_woman information_desk_person sassy_woman]
	"💁‍♂", // man tipping hand, tags=[information], aliases=[tipping_hand_man sassy_man]
	"🙅", // person gesturing NO, tags=[stop halt], aliases=[no_good_woman no_good ng_woman]
	"🙅‍♂", // man gesturing NO, tags=[stop halt], aliases=[no_good_man ng_man]
	"🙆", // person gesturing OK, tags=[], aliases=[ok_woman]
	"🙆‍♂", // man gesturing OK, tags=[], aliases=[ok_man]
	"🙋", // person raising hand, tags=[], aliases=[raising_hand_woman raising_hand]
	"🙋‍♂", // man raising hand, tags=[], aliases=[raising_hand_man]
	"🤦‍♀", // woman facepalming, tags=[], aliases=[woman_facepalming]
	"🤦‍♂", // man facepalming, tags=[], aliases=[man_facepalming]
	"🤷‍♀", // woman shrugging, tags=[], aliases=[woman_shrugging]
	"🤷‍♂", // man shrugging, tags=[], aliases=[man_shrugging]
	"🙎", // person pouting, tags=[], aliases=[pouting_woman person_with_pouting_face]
	"🙎‍♂", // man pouting, tags=[], aliases=[pouting_man]
	"🙍", // person frowning, tags=[sad], aliases=[frowning_woman person_frowning]
	"🙍‍♂", // man frowning, tags=[], aliases=[frowning_man]
	"💇", // person getting haircut, tags=[beauty], aliases=[haircut_woman haircut]
	"💇‍♂", // man getting haircut, tags=[], aliases=[haircut_man]
	"💆", // person getting massage, tags=[spa], aliases=[massage_woman massage]
	"💆‍♂", // man getting massage, tags=[spa], aliases=[massage_man]
	"🕴", // man in business suit levitating, tags=[], aliases=[business_suit_levitating]
	"💃", // woman dancing, tags=[dress], aliases=[dancer]
	"🕺", // man dancing, tags=[dancer], aliases=[man_dancing]
	"👯", // people with bunny ears partying, tags=[bunny], aliases=[dancing_women dancers]
	"👯‍♂", // men with bunny ears partying, tags=[bunny], aliases=[dancing_men]
	"🚶‍♀", // woman walking, tags=[], aliases=[walking_woman]
	"🚶", // person walking, tags=[], aliases=[walking_man walking]
	"🏃‍♀", // woman running, tags=[exercise workout marathon], aliases=[running_woman]
	"🏃", // person running, tags=[exercise workout marathon], aliases=[running_man runner running]
	"👫", // man and woman holding hands, tags=[date], aliases=[couple]
	"👭", // two women holding hands, tags=[couple date], aliases=[two_women_holding_hands]
	"👬", // two men holding hands, tags=[couple date], aliases=[two_men_holding_hands]
	"💑", // couple with heart, tags=[], aliases=[couple_with_heart_woman_man couple_with_heart]
	"👩‍❤️‍👩", // couple with heart: woman, woman, tags=[], aliases=[couple_with_heart_woman_woman]
	"👨‍❤️‍👨", // couple with heart: man, man, tags=[], aliases=[couple_with_heart_man_man]
	"💏", // kiss, tags=[], aliases=[couplekiss_man_woman]
	"👩‍❤️‍💋‍👩", // kiss: woman, woman, tags=[], aliases=[couplekiss_woman_woman]
	"👨‍❤️‍💋‍👨", // kiss: man, man, tags=[], aliases=[couplekiss_man_man]
	"👪", // family, tags=[home parents child], aliases=[family_man_woman_boy family]
	"👨‍👩‍👧", // family: man, woman, girl, tags=[], aliases=[family_man_woman_girl]
	"👨‍👩‍👧‍👦", // family: man, woman, girl, boy, tags=[], aliases=[family_man_woman_girl_boy]
	"👨‍👩‍👦‍👦", // family: man, woman, boy, boy, tags=[], aliases=[family_man_woman_boy_boy]
	"👨‍👩‍👧‍👧", // family: man, woman, girl, girl, tags=[], aliases=[family_man_woman_girl_girl]
	"👩‍👩‍👦", // family: woman, woman, boy, tags=[], aliases=[family_woman_woman_boy]
	"👩‍👩‍👧", // family: woman, woman, girl, tags=[], aliases=[family_woman_woman_girl]
	"👩‍👩‍👧‍👦", // family: woman, woman, girl, boy, tags=[], aliases=[family_woman_woman_girl_boy]
	"👩‍👩‍👦‍👦", // family: woman, woman, boy, boy, tags=[], aliases=[family_woman_woman_boy_boy]
	"👩‍👩‍👧‍👧", // family: woman, woman, girl, girl, tags=[], aliases=[family_woman_woman_girl_girl]
	"👨‍👨‍👦", // family: man, man, boy, tags=[], aliases=[family_man_man_boy]
	"👨‍👨‍👧", // family: man, man, girl, tags=[], aliases=[family_man_man_girl]
	"👨‍👨‍👧‍👦", // family: man, man, girl, boy, tags=[], aliases=[family_man_man_girl_boy]
	"👨‍👨‍👦‍👦", // family: man, man, boy, boy, tags=[], aliases=[family_man_man_boy_boy]
	"👨‍👨‍👧‍👧", // family: man, man, girl, girl, tags=[], aliases=[family_man_man_girl_girl]
	"👩‍👦", // family: woman, boy, tags=[], aliases=[family_woman_boy]
	"👩‍👧", // family: woman, girl, tags=[], aliases=[family_woman_girl]
	"👩‍👧‍👦", // family: woman, girl, boy, tags=[], aliases=[family_woman_girl_boy]
	"👩‍👦‍👦", // family: woman, boy, boy, tags=[], aliases=[family_woman_boy_boy]
	"👩‍👧‍👧", // family: woman, girl, girl, tags=[], aliases=[family_woman_girl_girl]
	"👨‍👦", // family: man, boy, tags=[], aliases=[family_man_boy]
	"👨‍👧", // family: man, girl, tags=[], aliases=[family_man_girl]
	"👨‍👧‍👦", // family: man, girl, boy, tags=[], aliases=[family_man_girl_boy]
	"👨‍👦‍👦", // family: man, boy, boy, tags=[], aliases=[family_man_boy_boy]
	"👨‍👧‍👧", // family: man, girl, girl, tags=[], aliases=[family_man_girl_girl]
	"👚", // woman’s clothes, tags=[], aliases=[womans_clothes]
	"👕", // t-shirt, tags=[], aliases=[shirt tshirt]
	"👖", // jeans, tags=[pants], aliases=[jeans]
	"👔", // necktie, tags=[shirt formal], aliases=[necktie]
	"👗", // dress, tags=[], aliases=[dress]
	"👙", // bikini, tags=[beach], aliases=[bikini]
	"👘", // kimono, tags=[], aliases=[kimono]
	"👠", // high-heeled shoe, tags=[shoe], aliases=[high_heel]
	"👡", // woman’s sandal, tags=[shoe], aliases=[sandal]
	"👢", // woman’s boot, tags=[], aliases=[boot]
	"👞", // man’s shoe, tags=[], aliases=[mans_shoe shoe]
	"👟", // running shoe, tags=[sneaker sport running], aliases=[athletic_shoe]
	"👒", // woman’s hat, tags=[], aliases=[womans_hat]
	"🎩", // top hat, tags=[hat classy], aliases=[tophat]
	"🎓", // graduation cap, tags=[education college university graduation], aliases=[mortar_board]
	"👑", // crown, tags=[king queen royal], aliases=[crown]
	"⛑", // rescue worker’s helmet, tags=[], aliases=[rescue_worker_helmet]
	"🎒", // school backpack, tags=[], aliases=[school_satchel]
	"👝", // clutch bag, tags=[bag], aliases=[pouch]
	"👛", // purse, tags=[], aliases=[purse]
	"👜", // handbag, tags=[bag], aliases=[handbag]
	"💼", // briefcase, tags=[business], aliases=[briefcase]
	"👓", // glasses, tags=[glasses], aliases=[eyeglasses]
	"🕶", // sunglasses, tags=[], aliases=[dark_sunglasses]
	"🌂", // closed umbrella, tags=[weather rain], aliases=[closed_umbrella]
	"☂️", // umbrella, tags=[], aliases=[open_umbrella]
}
