package emojis

var ByCategory = map[string][]string {
	"activity": CategoryActivity,
	"flags": CategoryFlags,
	"foods": CategoryFoods,
	"nature": CategoryNature,
	"objects": CategoryObjects,
	"people": CategoryPeople,
	"places": CategoryPlaces,
	"symbols": CategorySymbols,
}

var All = map[string]Info {
	"😀": {Description: "grinning face", Category: "People"},
	"😃": {Description: "smiling face with open mouth", Category: "People"},
	"😄": {Description: "smiling face with open mouth & smiling eyes", Category: "People"},
	"😁": {Description: "grinning face with smiling eyes", Category: "People"},
	"😆": {Description: "smiling face with open mouth & closed eyes", Category: "People"},
	"😅": {Description: "smiling face with open mouth & cold sweat", Category: "People"},
	"😂": {Description: "face with tears of joy", Category: "People"},
	"🤣": {Description: "rolling on the floor laughing", Category: "People"},
	"☺️": {Description: "smiling face", Category: "People"},
	"😊": {Description: "smiling face with smiling eyes", Category: "People"},
	"😇": {Description: "smiling face with halo", Category: "People"},
	"🙂": {Description: "slightly smiling face", Category: "People"},
	"🙃": {Description: "upside-down face", Category: "People"},
	"😉": {Description: "winking face", Category: "People"},
	"😌": {Description: "relieved face", Category: "People"},
	"😍": {Description: "smiling face with heart-eyes", Category: "People"},
	"😘": {Description: "face blowing a kiss", Category: "People"},
	"😗": {Description: "kissing face", Category: "People"},
	"😙": {Description: "kissing face with smiling eyes", Category: "People"},
	"😚": {Description: "kissing face with closed eyes", Category: "People"},
	"😋": {Description: "face savouring delicious food", Category: "People"},
	"😜": {Description: "face with stuck-out tongue & winking eye", Category: "People"},
	"😝": {Description: "face with stuck-out tongue & closed eyes", Category: "People"},
	"😛": {Description: "face with stuck-out tongue", Category: "People"},
	"🤑": {Description: "money-mouth face", Category: "People"},
	"🤗": {Description: "hugging face", Category: "People"},
	"🤓": {Description: "nerd face", Category: "People"},
	"😎": {Description: "smiling face with sunglasses", Category: "People"},
	"🤡": {Description: "clown face", Category: "People"},
	"🤠": {Description: "cowboy hat face", Category: "People"},
	"😏": {Description: "smirking face", Category: "People"},
	"😒": {Description: "unamused face", Category: "People"},
	"😞": {Description: "disappointed face", Category: "People"},
	"😔": {Description: "pensive face", Category: "People"},
	"😟": {Description: "worried face", Category: "People"},
	"😕": {Description: "confused face", Category: "People"},
	"🙁": {Description: "slightly frowning face", Category: "People"},
	"☹️": {Description: "frowning face", Category: "People"},
	"😣": {Description: "persevering face", Category: "People"},
	"😖": {Description: "confounded face", Category: "People"},
	"😫": {Description: "tired face", Category: "People"},
	"😩": {Description: "weary face", Category: "People"},
	"😤": {Description: "face with steam from nose", Category: "People"},
	"😠": {Description: "angry face", Category: "People"},
	"😡": {Description: "pouting face", Category: "People"},
	"😶": {Description: "face without mouth", Category: "People"},
	"😐": {Description: "neutral face", Category: "People"},
	"😑": {Description: "expressionless face", Category: "People"},
	"😯": {Description: "hushed face", Category: "People"},
	"😦": {Description: "frowning face with open mouth", Category: "People"},
	"😧": {Description: "anguished face", Category: "People"},
	"😮": {Description: "face with open mouth", Category: "People"},
	"😲": {Description: "astonished face", Category: "People"},
	"😵": {Description: "dizzy face", Category: "People"},
	"😳": {Description: "flushed face", Category: "People"},
	"😱": {Description: "face screaming in fear", Category: "People"},
	"😨": {Description: "fearful face", Category: "People"},
	"😰": {Description: "face with open mouth & cold sweat", Category: "People"},
	"😢": {Description: "crying face", Category: "People"},
	"😥": {Description: "disappointed but relieved face", Category: "People"},
	"🤤": {Description: "drooling face", Category: "People"},
	"😭": {Description: "loudly crying face", Category: "People"},
	"😓": {Description: "face with cold sweat", Category: "People"},
	"😪": {Description: "sleepy face", Category: "People"},
	"😴": {Description: "sleeping face", Category: "People"},
	"🙄": {Description: "face with rolling eyes", Category: "People"},
	"🤔": {Description: "thinking face", Category: "People"},
	"🤥": {Description: "lying face", Category: "People"},
	"😬": {Description: "grimacing face", Category: "People"},
	"🤐": {Description: "zipper-mouth face", Category: "People"},
	"🤢": {Description: "nauseated face", Category: "People"},
	"🤧": {Description: "sneezing face", Category: "People"},
	"😷": {Description: "face with medical mask", Category: "People"},
	"🤒": {Description: "face with thermometer", Category: "People"},
	"🤕": {Description: "face with head-bandage", Category: "People"},
	"😈": {Description: "smiling face with horns", Category: "People"},
	"👿": {Description: "angry face with horns", Category: "People"},
	"👹": {Description: "ogre", Category: "People"},
	"👺": {Description: "goblin", Category: "People"},
	"💩": {Description: "pile of poo", Category: "People"},
	"👻": {Description: "ghost", Category: "People"},
	"💀": {Description: "skull", Category: "People"},
	"☠️": {Description: "skull and crossbones", Category: "People"},
	"👽": {Description: "alien", Category: "People"},
	"👾": {Description: "alien monster", Category: "People"},
	"🤖": {Description: "robot face", Category: "People"},
	"🎃": {Description: "jack-o-lantern", Category: "People"},
	"😺": {Description: "smiling cat face with open mouth", Category: "People"},
	"😸": {Description: "grinning cat face with smiling eyes", Category: "People"},
	"😹": {Description: "cat face with tears of joy", Category: "People"},
	"😻": {Description: "smiling cat face with heart-eyes", Category: "People"},
	"😼": {Description: "cat face with wry smile", Category: "People"},
	"😽": {Description: "kissing cat face with closed eyes", Category: "People"},
	"🙀": {Description: "weary cat face", Category: "People"},
	"😿": {Description: "crying cat face", Category: "People"},
	"😾": {Description: "pouting cat face", Category: "People"},
	"👐": {Description: "open hands", Category: "People"},
	"🙌": {Description: "raising hands", Category: "People"},
	"👏": {Description: "clapping hands", Category: "People"},
	"🙏": {Description: "folded hands", Category: "People"},
	"🤝": {Description: "handshake", Category: "People"},
	"👍": {Description: "thumbs up", Category: "People"},
	"👎": {Description: "thumbs down", Category: "People"},
	"👊": {Description: "oncoming fist", Category: "People"},
	"✊": {Description: "raised fist", Category: "People"},
	"🤛": {Description: "left-facing fist", Category: "People"},
	"🤜": {Description: "right-facing fist", Category: "People"},
	"🤞": {Description: "crossed fingers", Category: "People"},
	"✌️": {Description: "victory hand", Category: "People"},
	"🤘": {Description: "sign of the horns", Category: "People"},
	"👌": {Description: "OK hand", Category: "People"},
	"👈": {Description: "backhand index pointing left", Category: "People"},
	"👉": {Description: "backhand index pointing right", Category: "People"},
	"👆": {Description: "backhand index pointing up", Category: "People"},
	"👇": {Description: "backhand index pointing down", Category: "People"},
	"☝️": {Description: "index pointing up", Category: "People"},
	"✋": {Description: "raised hand", Category: "People"},
	"🤚": {Description: "raised back of hand", Category: "People"},
	"🖐": {Description: "raised hand with fingers splayed", Category: "People"},
	"🖖": {Description: "vulcan salute", Category: "People"},
	"👋": {Description: "waving hand", Category: "People"},
	"🤙": {Description: "call me hand", Category: "People"},
	"💪": {Description: "flexed biceps", Category: "People"},
	"🖕": {Description: "middle finger", Category: "People"},
	"✍️": {Description: "writing hand", Category: "People"},
	"🤳": {Description: "selfie", Category: "People"},
	"💅": {Description: "nail polish", Category: "People"},
	"💍": {Description: "ring", Category: "People"},
	"💄": {Description: "lipstick", Category: "People"},
	"💋": {Description: "kiss mark", Category: "People"},
	"👄": {Description: "mouth", Category: "People"},
	"👅": {Description: "tongue", Category: "People"},
	"👂": {Description: "ear", Category: "People"},
	"👃": {Description: "nose", Category: "People"},
	"👣": {Description: "footprints", Category: "People"},
	"👁": {Description: "eye", Category: "People"},
	"👀": {Description: "eyes", Category: "People"},
	"🗣": {Description: "speaking head", Category: "People"},
	"👤": {Description: "bust in silhouette", Category: "People"},
	"👥": {Description: "busts in silhouette", Category: "People"},
	"👶": {Description: "baby", Category: "People"},
	"👦": {Description: "boy", Category: "People"},
	"👧": {Description: "girl", Category: "People"},
	"👨": {Description: "man", Category: "People"},
	"👩": {Description: "woman", Category: "People"},
	"👱‍♀": {Description: "blond-haired woman", Category: "People"},
	"👱": {Description: "blond-haired person", Category: "People"},
	"👴": {Description: "old man", Category: "People"},
	"👵": {Description: "old woman", Category: "People"},
	"👲": {Description: "man with Chinese cap", Category: "People"},
	"👳‍♀": {Description: "woman wearing turban", Category: "People"},
	"👳": {Description: "person wearing turban", Category: "People"},
	"👮‍♀": {Description: "woman police officer", Category: "People"},
	"👮": {Description: "police officer", Category: "People"},
	"👷‍♀": {Description: "woman construction worker", Category: "People"},
	"👷": {Description: "construction worker", Category: "People"},
	"💂‍♀": {Description: "woman guard", Category: "People"},
	"💂": {Description: "guard", Category: "People"},
	"🕵️‍♀️": {Description: "woman detective", Category: "People"},
	"🕵": {Description: "detective", Category: "People"},
	"👩‍⚕": {Description: "woman health worker", Category: "People"},
	"👨‍⚕": {Description: "man health worker", Category: "People"},
	"👩‍🌾": {Description: "woman farmer", Category: "People"},
	"👨‍🌾": {Description: "man farmer", Category: "People"},
	"👩‍🍳": {Description: "woman cook", Category: "People"},
	"👨‍🍳": {Description: "man cook", Category: "People"},
	"👩‍🎓": {Description: "woman student", Category: "People"},
	"👨‍🎓": {Description: "man student", Category: "People"},
	"👩‍🎤": {Description: "woman singer", Category: "People"},
	"👨‍🎤": {Description: "man singer", Category: "People"},
	"👩‍🏫": {Description: "woman teacher", Category: "People"},
	"👨‍🏫": {Description: "man teacher", Category: "People"},
	"👩‍🏭": {Description: "woman factory worker", Category: "People"},
	"👨‍🏭": {Description: "man factory worker", Category: "People"},
	"👩‍💻": {Description: "woman technologist", Category: "People"},
	"👨‍💻": {Description: "man technologist", Category: "People"},
	"👩‍💼": {Description: "woman office worker", Category: "People"},
	"👨‍💼": {Description: "man office worker", Category: "People"},
	"👩‍🔧": {Description: "woman mechanic", Category: "People"},
	"👨‍🔧": {Description: "man mechanic", Category: "People"},
	"👩‍🔬": {Description: "woman scientist", Category: "People"},
	"👨‍🔬": {Description: "man scientist", Category: "People"},
	"👩‍🎨": {Description: "woman artist", Category: "People"},
	"👨‍🎨": {Description: "man artist", Category: "People"},
	"👩‍🚒": {Description: "woman firefighter", Category: "People"},
	"👨‍🚒": {Description: "man firefighter", Category: "People"},
	"👩‍✈": {Description: "woman pilot", Category: "People"},
	"👨‍✈": {Description: "man pilot", Category: "People"},
	"👩‍🚀": {Description: "woman astronaut", Category: "People"},
	"👨‍🚀": {Description: "man astronaut", Category: "People"},
	"👩‍⚖": {Description: "woman judge", Category: "People"},
	"👨‍⚖": {Description: "man judge", Category: "People"},
	"🤶": {Description: "Mrs. Claus", Category: "People"},
	"🎅": {Description: "Santa Claus", Category: "People"},
	"👸": {Description: "princess", Category: "People"},
	"🤴": {Description: "prince", Category: "People"},
	"👰": {Description: "bride with veil", Category: "People"},
	"🤵": {Description: "man in tuxedo", Category: "People"},
	"👼": {Description: "baby angel", Category: "People"},
	"🤰": {Description: "pregnant woman", Category: "People"},
	"🙇‍♀": {Description: "woman bowing", Category: "People"},
	"🙇": {Description: "person bowing", Category: "People"},
	"💁": {Description: "person tipping hand", Category: "People"},
	"💁‍♂": {Description: "man tipping hand", Category: "People"},
	"🙅": {Description: "person gesturing NO", Category: "People"},
	"🙅‍♂": {Description: "man gesturing NO", Category: "People"},
	"🙆": {Description: "person gesturing OK", Category: "People"},
	"🙆‍♂": {Description: "man gesturing OK", Category: "People"},
	"🙋": {Description: "person raising hand", Category: "People"},
	"🙋‍♂": {Description: "man raising hand", Category: "People"},
	"🤦‍♀": {Description: "woman facepalming", Category: "People"},
	"🤦‍♂": {Description: "man facepalming", Category: "People"},
	"🤷‍♀": {Description: "woman shrugging", Category: "People"},
	"🤷‍♂": {Description: "man shrugging", Category: "People"},
	"🙎": {Description: "person pouting", Category: "People"},
	"🙎‍♂": {Description: "man pouting", Category: "People"},
	"🙍": {Description: "person frowning", Category: "People"},
	"🙍‍♂": {Description: "man frowning", Category: "People"},
	"💇": {Description: "person getting haircut", Category: "People"},
	"💇‍♂": {Description: "man getting haircut", Category: "People"},
	"💆": {Description: "person getting massage", Category: "People"},
	"💆‍♂": {Description: "man getting massage", Category: "People"},
	"🕴": {Description: "man in business suit levitating", Category: "People"},
	"💃": {Description: "woman dancing", Category: "People"},
	"🕺": {Description: "man dancing", Category: "People"},
	"👯": {Description: "people with bunny ears partying", Category: "People"},
	"👯‍♂": {Description: "men with bunny ears partying", Category: "People"},
	"🚶‍♀": {Description: "woman walking", Category: "People"},
	"🚶": {Description: "person walking", Category: "People"},
	"🏃‍♀": {Description: "woman running", Category: "People"},
	"🏃": {Description: "person running", Category: "People"},
	"👫": {Description: "man and woman holding hands", Category: "People"},
	"👭": {Description: "two women holding hands", Category: "People"},
	"👬": {Description: "two men holding hands", Category: "People"},
	"💑": {Description: "couple with heart", Category: "People"},
	"👩‍❤️‍👩": {Description: "couple with heart: woman, woman", Category: "People"},
	"👨‍❤️‍👨": {Description: "couple with heart: man, man", Category: "People"},
	"💏": {Description: "kiss", Category: "People"},
	"👩‍❤️‍💋‍👩": {Description: "kiss: woman, woman", Category: "People"},
	"👨‍❤️‍💋‍👨": {Description: "kiss: man, man", Category: "People"},
	"👪": {Description: "family", Category: "People"},
	"👨‍👩‍👧": {Description: "family: man, woman, girl", Category: "People"},
	"👨‍👩‍👧‍👦": {Description: "family: man, woman, girl, boy", Category: "People"},
	"👨‍👩‍👦‍👦": {Description: "family: man, woman, boy, boy", Category: "People"},
	"👨‍👩‍👧‍👧": {Description: "family: man, woman, girl, girl", Category: "People"},
	"👩‍👩‍👦": {Description: "family: woman, woman, boy", Category: "People"},
	"👩‍👩‍👧": {Description: "family: woman, woman, girl", Category: "People"},
	"👩‍👩‍👧‍👦": {Description: "family: woman, woman, girl, boy", Category: "People"},
	"👩‍👩‍👦‍👦": {Description: "family: woman, woman, boy, boy", Category: "People"},
	"👩‍👩‍👧‍👧": {Description: "family: woman, woman, girl, girl", Category: "People"},
	"👨‍👨‍👦": {Description: "family: man, man, boy", Category: "People"},
	"👨‍👨‍👧": {Description: "family: man, man, girl", Category: "People"},
	"👨‍👨‍👧‍👦": {Description: "family: man, man, girl, boy", Category: "People"},
	"👨‍👨‍👦‍👦": {Description: "family: man, man, boy, boy", Category: "People"},
	"👨‍👨‍👧‍👧": {Description: "family: man, man, girl, girl", Category: "People"},
	"👩‍👦": {Description: "family: woman, boy", Category: "People"},
	"👩‍👧": {Description: "family: woman, girl", Category: "People"},
	"👩‍👧‍👦": {Description: "family: woman, girl, boy", Category: "People"},
	"👩‍👦‍👦": {Description: "family: woman, boy, boy", Category: "People"},
	"👩‍👧‍👧": {Description: "family: woman, girl, girl", Category: "People"},
	"👨‍👦": {Description: "family: man, boy", Category: "People"},
	"👨‍👧": {Description: "family: man, girl", Category: "People"},
	"👨‍👧‍👦": {Description: "family: man, girl, boy", Category: "People"},
	"👨‍👦‍👦": {Description: "family: man, boy, boy", Category: "People"},
	"👨‍👧‍👧": {Description: "family: man, girl, girl", Category: "People"},
	"👚": {Description: "woman’s clothes", Category: "People"},
	"👕": {Description: "t-shirt", Category: "People"},
	"👖": {Description: "jeans", Category: "People"},
	"👔": {Description: "necktie", Category: "People"},
	"👗": {Description: "dress", Category: "People"},
	"👙": {Description: "bikini", Category: "People"},
	"👘": {Description: "kimono", Category: "People"},
	"👠": {Description: "high-heeled shoe", Category: "People"},
	"👡": {Description: "woman’s sandal", Category: "People"},
	"👢": {Description: "woman’s boot", Category: "People"},
	"👞": {Description: "man’s shoe", Category: "People"},
	"👟": {Description: "running shoe", Category: "People"},
	"👒": {Description: "woman’s hat", Category: "People"},
	"🎩": {Description: "top hat", Category: "People"},
	"🎓": {Description: "graduation cap", Category: "People"},
	"👑": {Description: "crown", Category: "People"},
	"⛑": {Description: "rescue worker’s helmet", Category: "People"},
	"🎒": {Description: "school backpack", Category: "People"},
	"👝": {Description: "clutch bag", Category: "People"},
	"👛": {Description: "purse", Category: "People"},
	"👜": {Description: "handbag", Category: "People"},
	"💼": {Description: "briefcase", Category: "People"},
	"👓": {Description: "glasses", Category: "People"},
	"🕶": {Description: "sunglasses", Category: "People"},
	"🌂": {Description: "closed umbrella", Category: "People"},
	"☂️": {Description: "umbrella", Category: "People"},
	"🐶": {Description: "dog face", Category: "Nature"},
	"🐱": {Description: "cat face", Category: "Nature"},
	"🐭": {Description: "mouse face", Category: "Nature"},
	"🐹": {Description: "hamster face", Category: "Nature"},
	"🐰": {Description: "rabbit face", Category: "Nature"},
	"🦊": {Description: "fox face", Category: "Nature"},
	"🐻": {Description: "bear face", Category: "Nature"},
	"🐼": {Description: "panda face", Category: "Nature"},
	"🐨": {Description: "koala", Category: "Nature"},
	"🐯": {Description: "tiger face", Category: "Nature"},
	"🦁": {Description: "lion face", Category: "Nature"},
	"🐮": {Description: "cow face", Category: "Nature"},
	"🐷": {Description: "pig face", Category: "Nature"},
	"🐽": {Description: "pig nose", Category: "Nature"},
	"🐸": {Description: "frog face", Category: "Nature"},
	"🐵": {Description: "monkey face", Category: "Nature"},
	"🙈": {Description: "see-no-evil monkey", Category: "Nature"},
	"🙉": {Description: "hear-no-evil monkey", Category: "Nature"},
	"🙊": {Description: "speak-no-evil monkey", Category: "Nature"},
	"🐒": {Description: "monkey", Category: "Nature"},
	"🐔": {Description: "chicken", Category: "Nature"},
	"🐧": {Description: "penguin", Category: "Nature"},
	"🐦": {Description: "bird", Category: "Nature"},
	"🐤": {Description: "baby chick", Category: "Nature"},
	"🐣": {Description: "hatching chick", Category: "Nature"},
	"🐥": {Description: "front-facing baby chick", Category: "Nature"},
	"🦆": {Description: "duck", Category: "Nature"},
	"🦅": {Description: "eagle", Category: "Nature"},
	"🦉": {Description: "owl", Category: "Nature"},
	"🦇": {Description: "bat", Category: "Nature"},
	"🐺": {Description: "wolf face", Category: "Nature"},
	"🐗": {Description: "boar", Category: "Nature"},
	"🐴": {Description: "horse face", Category: "Nature"},
	"🦄": {Description: "unicorn face", Category: "Nature"},
	"🐝": {Description: "honeybee", Category: "Nature"},
	"🐛": {Description: "bug", Category: "Nature"},
	"🦋": {Description: "butterfly", Category: "Nature"},
	"🐌": {Description: "snail", Category: "Nature"},
	"🐚": {Description: "spiral shell", Category: "Nature"},
	"🐞": {Description: "lady beetle", Category: "Nature"},
	"🐜": {Description: "ant", Category: "Nature"},
	"🕷": {Description: "spider", Category: "Nature"},
	"🕸": {Description: "spider web", Category: "Nature"},
	"🐢": {Description: "turtle", Category: "Nature"},
	"🐍": {Description: "snake", Category: "Nature"},
	"🦎": {Description: "lizard", Category: "Nature"},
	"🦂": {Description: "scorpion", Category: "Nature"},
	"🦀": {Description: "crab", Category: "Nature"},
	"🦑": {Description: "squid", Category: "Nature"},
	"🐙": {Description: "octopus", Category: "Nature"},
	"🦐": {Description: "shrimp", Category: "Nature"},
	"🐠": {Description: "tropical fish", Category: "Nature"},
	"🐟": {Description: "fish", Category: "Nature"},
	"🐡": {Description: "blowfish", Category: "Nature"},
	"🐬": {Description: "dolphin", Category: "Nature"},
	"🦈": {Description: "shark", Category: "Nature"},
	"🐳": {Description: "spouting whale", Category: "Nature"},
	"🐋": {Description: "whale", Category: "Nature"},
	"🐊": {Description: "crocodile", Category: "Nature"},
	"🐆": {Description: "leopard", Category: "Nature"},
	"🐅": {Description: "tiger", Category: "Nature"},
	"🐃": {Description: "water buffalo", Category: "Nature"},
	"🐂": {Description: "ox", Category: "Nature"},
	"🐄": {Description: "cow", Category: "Nature"},
	"🦌": {Description: "deer", Category: "Nature"},
	"🐪": {Description: "camel", Category: "Nature"},
	"🐫": {Description: "two-hump camel", Category: "Nature"},
	"🐘": {Description: "elephant", Category: "Nature"},
	"🦏": {Description: "rhinoceros", Category: "Nature"},
	"🦍": {Description: "gorilla", Category: "Nature"},
	"🐎": {Description: "horse", Category: "Nature"},
	"🐖": {Description: "pig", Category: "Nature"},
	"🐐": {Description: "goat", Category: "Nature"},
	"🐏": {Description: "ram", Category: "Nature"},
	"🐑": {Description: "sheep", Category: "Nature"},
	"🐕": {Description: "dog", Category: "Nature"},
	"🐩": {Description: "poodle", Category: "Nature"},
	"🐈": {Description: "cat", Category: "Nature"},
	"🐓": {Description: "rooster", Category: "Nature"},
	"🦃": {Description: "turkey", Category: "Nature"},
	"🕊": {Description: "dove", Category: "Nature"},
	"🐇": {Description: "rabbit", Category: "Nature"},
	"🐁": {Description: "mouse", Category: "Nature"},
	"🐀": {Description: "rat", Category: "Nature"},
	"🐿": {Description: "chipmunk", Category: "Nature"},
	"🐾": {Description: "paw prints", Category: "Nature"},
	"🐉": {Description: "dragon", Category: "Nature"},
	"🐲": {Description: "dragon face", Category: "Nature"},
	"🌵": {Description: "cactus", Category: "Nature"},
	"🎄": {Description: "Christmas tree", Category: "Nature"},
	"🌲": {Description: "evergreen tree", Category: "Nature"},
	"🌳": {Description: "deciduous tree", Category: "Nature"},
	"🌴": {Description: "palm tree", Category: "Nature"},
	"🌱": {Description: "seedling", Category: "Nature"},
	"🌿": {Description: "herb", Category: "Nature"},
	"☘️": {Description: "shamrock", Category: "Nature"},
	"🍀": {Description: "four leaf clover", Category: "Nature"},
	"🎍": {Description: "pine decoration", Category: "Nature"},
	"🎋": {Description: "tanabata tree", Category: "Nature"},
	"🍃": {Description: "leaf fluttering in wind", Category: "Nature"},
	"🍂": {Description: "fallen leaf", Category: "Nature"},
	"🍁": {Description: "maple leaf", Category: "Nature"},
	"🍄": {Description: "mushroom", Category: "Nature"},
	"🌾": {Description: "sheaf of rice", Category: "Nature"},
	"💐": {Description: "bouquet", Category: "Nature"},
	"🌷": {Description: "tulip", Category: "Nature"},
	"🌹": {Description: "rose", Category: "Nature"},
	"🥀": {Description: "wilted flower", Category: "Nature"},
	"🌻": {Description: "sunflower", Category: "Nature"},
	"🌼": {Description: "blossom", Category: "Nature"},
	"🌸": {Description: "cherry blossom", Category: "Nature"},
	"🌺": {Description: "hibiscus", Category: "Nature"},
	"🌎": {Description: "globe showing Americas", Category: "Nature"},
	"🌍": {Description: "globe showing Europe-Africa", Category: "Nature"},
	"🌏": {Description: "globe showing Asia-Australia", Category: "Nature"},
	"🌕": {Description: "full moon", Category: "Nature"},
	"🌖": {Description: "waning gibbous moon", Category: "Nature"},
	"🌗": {Description: "last quarter moon", Category: "Nature"},
	"🌘": {Description: "waning crescent moon", Category: "Nature"},
	"🌑": {Description: "new moon", Category: "Nature"},
	"🌒": {Description: "waxing crescent moon", Category: "Nature"},
	"🌓": {Description: "first quarter moon", Category: "Nature"},
	"🌔": {Description: "waxing gibbous moon", Category: "Nature"},
	"🌚": {Description: "new moon face", Category: "Nature"},
	"🌝": {Description: "full moon with face", Category: "Nature"},
	"🌞": {Description: "sun with face", Category: "Nature"},
	"🌛": {Description: "first quarter moon with face", Category: "Nature"},
	"🌜": {Description: "last quarter moon with face", Category: "Nature"},
	"🌙": {Description: "crescent moon", Category: "Nature"},
	"💫": {Description: "dizzy", Category: "Nature"},
	"⭐️": {Description: "white medium star", Category: "Nature"},
	"🌟": {Description: "glowing star", Category: "Nature"},
	"✨": {Description: "sparkles", Category: "Nature"},
	"⚡️": {Description: "high voltage", Category: "Nature"},
	"🔥": {Description: "fire", Category: "Nature"},
	"💥": {Description: "collision", Category: "Nature"},
	"☄": {Description: "comet", Category: "Nature"},
	"☀️": {Description: "sun", Category: "Nature"},
	"🌤": {Description: "sun behind small cloud", Category: "Nature"},
	"⛅️": {Description: "sun behind cloud", Category: "Nature"},
	"🌥": {Description: "sun behind large cloud", Category: "Nature"},
	"🌦": {Description: "sun behind rain cloud", Category: "Nature"},
	"🌈": {Description: "rainbow", Category: "Nature"},
	"☁️": {Description: "cloud", Category: "Nature"},
	"🌧": {Description: "cloud with rain", Category: "Nature"},
	"⛈": {Description: "cloud with lightning and rain", Category: "Nature"},
	"🌩": {Description: "cloud with lightning", Category: "Nature"},
	"🌨": {Description: "cloud with snow", Category: "Nature"},
	"☃️": {Description: "snowman", Category: "Nature"},
	"⛄️": {Description: "snowman without snow", Category: "Nature"},
	"❄️": {Description: "snowflake", Category: "Nature"},
	"🌬": {Description: "wind face", Category: "Nature"},
	"💨": {Description: "dashing away", Category: "Nature"},
	"🌪": {Description: "tornado", Category: "Nature"},
	"🌫": {Description: "fog", Category: "Nature"},
	"🌊": {Description: "water wave", Category: "Nature"},
	"💧": {Description: "droplet", Category: "Nature"},
	"💦": {Description: "sweat droplets", Category: "Nature"},
	"☔️": {Description: "umbrella with rain drops", Category: "Nature"},
	"🍏": {Description: "green apple", Category: "Foods"},
	"🍎": {Description: "red apple", Category: "Foods"},
	"🍐": {Description: "pear", Category: "Foods"},
	"🍊": {Description: "tangerine", Category: "Foods"},
	"🍋": {Description: "lemon", Category: "Foods"},
	"🍌": {Description: "banana", Category: "Foods"},
	"🍉": {Description: "watermelon", Category: "Foods"},
	"🍇": {Description: "grapes", Category: "Foods"},
	"🍓": {Description: "strawberry", Category: "Foods"},
	"🍈": {Description: "melon", Category: "Foods"},
	"🍒": {Description: "cherries", Category: "Foods"},
	"🍑": {Description: "peach", Category: "Foods"},
	"🍍": {Description: "pineapple", Category: "Foods"},
	"🥝": {Description: "kiwi fruit", Category: "Foods"},
	"🥑": {Description: "avocado", Category: "Foods"},
	"🍅": {Description: "tomato", Category: "Foods"},
	"🍆": {Description: "eggplant", Category: "Foods"},
	"🥒": {Description: "cucumber", Category: "Foods"},
	"🥕": {Description: "carrot", Category: "Foods"},
	"🌽": {Description: "ear of corn", Category: "Foods"},
	"🌶": {Description: "hot pepper", Category: "Foods"},
	"🥔": {Description: "potato", Category: "Foods"},
	"🍠": {Description: "roasted sweet potato", Category: "Foods"},
	"🌰": {Description: "chestnut", Category: "Foods"},
	"🥜": {Description: "peanuts", Category: "Foods"},
	"🍯": {Description: "honey pot", Category: "Foods"},
	"🥐": {Description: "croissant", Category: "Foods"},
	"🍞": {Description: "bread", Category: "Foods"},
	"🥖": {Description: "baguette bread", Category: "Foods"},
	"🧀": {Description: "cheese wedge", Category: "Foods"},
	"🥚": {Description: "egg", Category: "Foods"},
	"🍳": {Description: "cooking", Category: "Foods"},
	"🥓": {Description: "bacon", Category: "Foods"},
	"🥞": {Description: "pancakes", Category: "Foods"},
	"🍤": {Description: "fried shrimp", Category: "Foods"},
	"🍗": {Description: "poultry leg", Category: "Foods"},
	"🍖": {Description: "meat on bone", Category: "Foods"},
	"🍕": {Description: "pizza", Category: "Foods"},
	"🌭": {Description: "hot dog", Category: "Foods"},
	"🍔": {Description: "hamburger", Category: "Foods"},
	"🍟": {Description: "french fries", Category: "Foods"},
	"🥙": {Description: "stuffed flatbread", Category: "Foods"},
	"🌮": {Description: "taco", Category: "Foods"},
	"🌯": {Description: "burrito", Category: "Foods"},
	"🥗": {Description: "green salad", Category: "Foods"},
	"🥘": {Description: "shallow pan of food", Category: "Foods"},
	"🍝": {Description: "spaghetti", Category: "Foods"},
	"🍜": {Description: "steaming bowl", Category: "Foods"},
	"🍲": {Description: "pot of food", Category: "Foods"},
	"🍥": {Description: "fish cake with swirl", Category: "Foods"},
	"🍣": {Description: "sushi", Category: "Foods"},
	"🍱": {Description: "bento box", Category: "Foods"},
	"🍛": {Description: "curry rice", Category: "Foods"},
	"🍚": {Description: "cooked rice", Category: "Foods"},
	"🍙": {Description: "rice ball", Category: "Foods"},
	"🍘": {Description: "rice cracker", Category: "Foods"},
	"🍢": {Description: "oden", Category: "Foods"},
	"🍡": {Description: "dango", Category: "Foods"},
	"🍧": {Description: "shaved ice", Category: "Foods"},
	"🍨": {Description: "ice cream", Category: "Foods"},
	"🍦": {Description: "soft ice cream", Category: "Foods"},
	"🍰": {Description: "shortcake", Category: "Foods"},
	"🎂": {Description: "birthday cake", Category: "Foods"},
	"🍮": {Description: "custard", Category: "Foods"},
	"🍭": {Description: "lollipop", Category: "Foods"},
	"🍬": {Description: "candy", Category: "Foods"},
	"🍫": {Description: "chocolate bar", Category: "Foods"},
	"🍿": {Description: "popcorn", Category: "Foods"},
	"🍩": {Description: "doughnut", Category: "Foods"},
	"🍪": {Description: "cookie", Category: "Foods"},
	"🥛": {Description: "glass of milk", Category: "Foods"},
	"🍼": {Description: "baby bottle", Category: "Foods"},
	"☕️": {Description: "hot beverage", Category: "Foods"},
	"🍵": {Description: "teacup without handle", Category: "Foods"},
	"🍶": {Description: "sake", Category: "Foods"},
	"🍺": {Description: "beer mug", Category: "Foods"},
	"🍻": {Description: "clinking beer mugs", Category: "Foods"},
	"🥂": {Description: "clinking glasses", Category: "Foods"},
	"🍷": {Description: "wine glass", Category: "Foods"},
	"🥃": {Description: "tumbler glass", Category: "Foods"},
	"🍸": {Description: "cocktail glass", Category: "Foods"},
	"🍹": {Description: "tropical drink", Category: "Foods"},
	"🍾": {Description: "bottle with popping cork", Category: "Foods"},
	"🥄": {Description: "spoon", Category: "Foods"},
	"🍴": {Description: "fork and knife", Category: "Foods"},
	"🍽": {Description: "fork and knife with plate", Category: "Foods"},
	"⚽️": {Description: "soccer ball", Category: "Activity"},
	"🏀": {Description: "basketball", Category: "Activity"},
	"🏈": {Description: "american football", Category: "Activity"},
	"⚾️": {Description: "baseball", Category: "Activity"},
	"🎾": {Description: "tennis", Category: "Activity"},
	"🏐": {Description: "volleyball", Category: "Activity"},
	"🏉": {Description: "rugby football", Category: "Activity"},
	"🎱": {Description: "pool 8 ball", Category: "Activity"},
	"🏓": {Description: "ping pong", Category: "Activity"},
	"🏸": {Description: "badminton", Category: "Activity"},
	"🥅": {Description: "goal net", Category: "Activity"},
	"🏒": {Description: "ice hockey", Category: "Activity"},
	"🏑": {Description: "field hockey", Category: "Activity"},
	"🏏": {Description: "cricket", Category: "Activity"},
	"⛳️": {Description: "flag in hole", Category: "Activity"},
	"🏹": {Description: "bow and arrow", Category: "Activity"},
	"🎣": {Description: "fishing pole", Category: "Activity"},
	"🥊": {Description: "boxing glove", Category: "Activity"},
	"🥋": {Description: "martial arts uniform", Category: "Activity"},
	"⛸": {Description: "ice skate", Category: "Activity"},
	"🎿": {Description: "skis", Category: "Activity"},
	"⛷": {Description: "skier", Category: "Activity"},
	"🏂": {Description: "snowboarder", Category: "Activity"},
	"🏋️‍♀️": {Description: "woman lifting weights", Category: "Activity"},
	"🏋": {Description: "person lifting weights", Category: "Activity"},
	"🤺": {Description: "person fencing", Category: "Activity"},
	"🤼‍♀": {Description: "women wrestling", Category: "Activity"},
	"🤼‍♂": {Description: "men wrestling", Category: "Activity"},
	"🤸‍♀": {Description: "woman cartwheeling", Category: "Activity"},
	"🤸‍♂": {Description: "man cartwheeling", Category: "Activity"},
	"⛹️‍♀️": {Description: "woman bouncing ball", Category: "Activity"},
	"⛹": {Description: "person bouncing ball", Category: "Activity"},
	"🤾‍♀": {Description: "woman playing handball", Category: "Activity"},
	"🤾‍♂": {Description: "man playing handball", Category: "Activity"},
	"🏌️‍♀️": {Description: "woman golfing", Category: "Activity"},
	"🏌": {Description: "person golfing", Category: "Activity"},
	"🏄‍♀": {Description: "woman surfing", Category: "Activity"},
	"🏄": {Description: "person surfing", Category: "Activity"},
	"🏊‍♀": {Description: "woman swimming", Category: "Activity"},
	"🏊": {Description: "person swimming", Category: "Activity"},
	"🤽‍♀": {Description: "woman playing water polo", Category: "Activity"},
	"🤽‍♂": {Description: "man playing water polo", Category: "Activity"},
	"🚣‍♀": {Description: "woman rowing boat", Category: "Activity"},
	"🚣": {Description: "person rowing boat", Category: "Activity"},
	"🏇": {Description: "horse racing", Category: "Activity"},
	"🚴‍♀": {Description: "woman biking", Category: "Activity"},
	"🚴": {Description: "person biking", Category: "Activity"},
	"🚵‍♀": {Description: "woman mountain biking", Category: "Activity"},
	"🚵": {Description: "person mountain biking", Category: "Activity"},
	"🎽": {Description: "running shirt", Category: "Activity"},
	"🏅": {Description: "sports medal", Category: "Activity"},
	"🎖": {Description: "military medal", Category: "Activity"},
	"🥇": {Description: "1st place medal", Category: "Activity"},
	"🥈": {Description: "2nd place medal", Category: "Activity"},
	"🥉": {Description: "3rd place medal", Category: "Activity"},
	"🏆": {Description: "trophy", Category: "Activity"},
	"🏵": {Description: "rosette", Category: "Activity"},
	"🎗": {Description: "reminder ribbon", Category: "Activity"},
	"🎫": {Description: "ticket", Category: "Activity"},
	"🎟": {Description: "admission tickets", Category: "Activity"},
	"🎪": {Description: "circus tent", Category: "Activity"},
	"🤹‍♀": {Description: "woman juggling", Category: "Activity"},
	"🤹‍♂": {Description: "man juggling", Category: "Activity"},
	"🎭": {Description: "performing arts", Category: "Activity"},
	"🎨": {Description: "artist palette", Category: "Activity"},
	"🎬": {Description: "clapper board", Category: "Activity"},
	"🎤": {Description: "microphone", Category: "Activity"},
	"🎧": {Description: "headphone", Category: "Activity"},
	"🎼": {Description: "musical score", Category: "Activity"},
	"🎹": {Description: "musical keyboard", Category: "Activity"},
	"🥁": {Description: "drum", Category: "Activity"},
	"🎷": {Description: "saxophone", Category: "Activity"},
	"🎺": {Description: "trumpet", Category: "Activity"},
	"🎸": {Description: "guitar", Category: "Activity"},
	"🎻": {Description: "violin", Category: "Activity"},
	"🎲": {Description: "game die", Category: "Activity"},
	"🎯": {Description: "direct hit", Category: "Activity"},
	"🎳": {Description: "bowling", Category: "Activity"},
	"🎮": {Description: "video game", Category: "Activity"},
	"🎰": {Description: "slot machine", Category: "Activity"},
	"🚗": {Description: "automobile", Category: "Places"},
	"🚕": {Description: "taxi", Category: "Places"},
	"🚙": {Description: "sport utility vehicle", Category: "Places"},
	"🚌": {Description: "bus", Category: "Places"},
	"🚎": {Description: "trolleybus", Category: "Places"},
	"🏎": {Description: "racing car", Category: "Places"},
	"🚓": {Description: "police car", Category: "Places"},
	"🚑": {Description: "ambulance", Category: "Places"},
	"🚒": {Description: "fire engine", Category: "Places"},
	"🚐": {Description: "minibus", Category: "Places"},
	"🚚": {Description: "delivery truck", Category: "Places"},
	"🚛": {Description: "articulated lorry", Category: "Places"},
	"🚜": {Description: "tractor", Category: "Places"},
	"🛴": {Description: "kick scooter", Category: "Places"},
	"🚲": {Description: "bicycle", Category: "Places"},
	"🛵": {Description: "motor scooter", Category: "Places"},
	"🏍": {Description: "motorcycle", Category: "Places"},
	"🚨": {Description: "police car light", Category: "Places"},
	"🚔": {Description: "oncoming police car", Category: "Places"},
	"🚍": {Description: "oncoming bus", Category: "Places"},
	"🚘": {Description: "oncoming automobile", Category: "Places"},
	"🚖": {Description: "oncoming taxi", Category: "Places"},
	"🚡": {Description: "aerial tramway", Category: "Places"},
	"🚠": {Description: "mountain cableway", Category: "Places"},
	"🚟": {Description: "suspension railway", Category: "Places"},
	"🚃": {Description: "railway car", Category: "Places"},
	"🚋": {Description: "tram car", Category: "Places"},
	"🚞": {Description: "mountain railway", Category: "Places"},
	"🚝": {Description: "monorail", Category: "Places"},
	"🚄": {Description: "high-speed train", Category: "Places"},
	"🚅": {Description: "high-speed train with bullet nose", Category: "Places"},
	"🚈": {Description: "light rail", Category: "Places"},
	"🚂": {Description: "locomotive", Category: "Places"},
	"🚆": {Description: "train", Category: "Places"},
	"🚇": {Description: "metro", Category: "Places"},
	"🚊": {Description: "tram", Category: "Places"},
	"🚉": {Description: "station", Category: "Places"},
	"🚁": {Description: "helicopter", Category: "Places"},
	"🛩": {Description: "small airplane", Category: "Places"},
	"✈️": {Description: "airplane", Category: "Places"},
	"🛫": {Description: "airplane departure", Category: "Places"},
	"🛬": {Description: "airplane arrival", Category: "Places"},
	"🚀": {Description: "rocket", Category: "Places"},
	"🛰": {Description: "satellite", Category: "Places"},
	"💺": {Description: "seat", Category: "Places"},
	"🛶": {Description: "canoe", Category: "Places"},
	"⛵️": {Description: "sailboat", Category: "Places"},
	"🛥": {Description: "motor boat", Category: "Places"},
	"🚤": {Description: "speedboat", Category: "Places"},
	"🛳": {Description: "passenger ship", Category: "Places"},
	"⛴": {Description: "ferry", Category: "Places"},
	"🚢": {Description: "ship", Category: "Places"},
	"⚓️": {Description: "anchor", Category: "Places"},
	"🚧": {Description: "construction", Category: "Places"},
	"⛽️": {Description: "fuel pump", Category: "Places"},
	"🚏": {Description: "bus stop", Category: "Places"},
	"🚦": {Description: "vertical traffic light", Category: "Places"},
	"🚥": {Description: "horizontal traffic light", Category: "Places"},
	"🗺": {Description: "world map", Category: "Places"},
	"🗿": {Description: "moai", Category: "Places"},
	"🗽": {Description: "Statue of Liberty", Category: "Places"},
	"⛲️": {Description: "fountain", Category: "Places"},
	"🗼": {Description: "Tokyo tower", Category: "Places"},
	"🏰": {Description: "castle", Category: "Places"},
	"🏯": {Description: "Japanese castle", Category: "Places"},
	"🏟": {Description: "stadium", Category: "Places"},
	"🎡": {Description: "ferris wheel", Category: "Places"},
	"🎢": {Description: "roller coaster", Category: "Places"},
	"🎠": {Description: "carousel horse", Category: "Places"},
	"⛱": {Description: "umbrella on ground", Category: "Places"},
	"🏖": {Description: "beach with umbrella", Category: "Places"},
	"🏝": {Description: "desert island", Category: "Places"},
	"⛰": {Description: "mountain", Category: "Places"},
	"🏔": {Description: "snow-capped mountain", Category: "Places"},
	"🗻": {Description: "mount fuji", Category: "Places"},
	"🌋": {Description: "volcano", Category: "Places"},
	"🏜": {Description: "desert", Category: "Places"},
	"🏕": {Description: "camping", Category: "Places"},
	"⛺️": {Description: "tent", Category: "Places"},
	"🛤": {Description: "railway track", Category: "Places"},
	"🛣": {Description: "motorway", Category: "Places"},
	"🏗": {Description: "building construction", Category: "Places"},
	"🏭": {Description: "factory", Category: "Places"},
	"🏠": {Description: "house", Category: "Places"},
	"🏡": {Description: "house with garden", Category: "Places"},
	"🏘": {Description: "house", Category: "Places"},
	"🏚": {Description: "derelict house", Category: "Places"},
	"🏢": {Description: "office building", Category: "Places"},
	"🏬": {Description: "department store", Category: "Places"},
	"🏣": {Description: "Japanese post office", Category: "Places"},
	"🏤": {Description: "post office", Category: "Places"},
	"🏥": {Description: "hospital", Category: "Places"},
	"🏦": {Description: "bank", Category: "Places"},
	"🏨": {Description: "hotel", Category: "Places"},
	"🏪": {Description: "convenience store", Category: "Places"},
	"🏫": {Description: "school", Category: "Places"},
	"🏩": {Description: "love hotel", Category: "Places"},
	"💒": {Description: "wedding", Category: "Places"},
	"🏛": {Description: "classical building", Category: "Places"},
	"⛪️": {Description: "church", Category: "Places"},
	"🕌": {Description: "mosque", Category: "Places"},
	"🕍": {Description: "synagogue", Category: "Places"},
	"🕋": {Description: "kaaba", Category: "Places"},
	"⛩": {Description: "shinto shrine", Category: "Places"},
	"🗾": {Description: "map of Japan", Category: "Places"},
	"🎑": {Description: "moon viewing ceremony", Category: "Places"},
	"🏞": {Description: "national park", Category: "Places"},
	"🌅": {Description: "sunrise", Category: "Places"},
	"🌄": {Description: "sunrise over mountains", Category: "Places"},
	"🌠": {Description: "shooting star", Category: "Places"},
	"🎇": {Description: "sparkler", Category: "Places"},
	"🎆": {Description: "fireworks", Category: "Places"},
	"🌇": {Description: "sunset", Category: "Places"},
	"🌆": {Description: "cityscape at dusk", Category: "Places"},
	"🏙": {Description: "cityscape", Category: "Places"},
	"🌃": {Description: "night with stars", Category: "Places"},
	"🌌": {Description: "milky way", Category: "Places"},
	"🌉": {Description: "bridge at night", Category: "Places"},
	"🌁": {Description: "foggy", Category: "Places"},
	"⌚️": {Description: "watch", Category: "Objects"},
	"📱": {Description: "mobile phone", Category: "Objects"},
	"📲": {Description: "mobile phone with arrow", Category: "Objects"},
	"💻": {Description: "laptop computer", Category: "Objects"},
	"⌨️": {Description: "keyboard", Category: "Objects"},
	"🖥": {Description: "desktop computer", Category: "Objects"},
	"🖨": {Description: "printer", Category: "Objects"},
	"🖱": {Description: "computer mouse", Category: "Objects"},
	"🖲": {Description: "trackball", Category: "Objects"},
	"🕹": {Description: "joystick", Category: "Objects"},
	"🗜": {Description: "clamp", Category: "Objects"},
	"💽": {Description: "computer disk", Category: "Objects"},
	"💾": {Description: "floppy disk", Category: "Objects"},
	"💿": {Description: "optical disk", Category: "Objects"},
	"📀": {Description: "dvd", Category: "Objects"},
	"📼": {Description: "videocassette", Category: "Objects"},
	"📷": {Description: "camera", Category: "Objects"},
	"📸": {Description: "camera with flash", Category: "Objects"},
	"📹": {Description: "video camera", Category: "Objects"},
	"🎥": {Description: "movie camera", Category: "Objects"},
	"📽": {Description: "film projector", Category: "Objects"},
	"🎞": {Description: "film frames", Category: "Objects"},
	"📞": {Description: "telephone receiver", Category: "Objects"},
	"☎️": {Description: "telephone", Category: "Objects"},
	"📟": {Description: "pager", Category: "Objects"},
	"📠": {Description: "fax machine", Category: "Objects"},
	"📺": {Description: "television", Category: "Objects"},
	"📻": {Description: "radio", Category: "Objects"},
	"🎙": {Description: "studio microphone", Category: "Objects"},
	"🎚": {Description: "level slider", Category: "Objects"},
	"🎛": {Description: "control knobs", Category: "Objects"},
	"⏱": {Description: "stopwatch", Category: "Objects"},
	"⏲": {Description: "timer clock", Category: "Objects"},
	"⏰": {Description: "alarm clock", Category: "Objects"},
	"🕰": {Description: "mantelpiece clock", Category: "Objects"},
	"⌛️": {Description: "hourglass", Category: "Objects"},
	"⏳": {Description: "hourglass with flowing sand", Category: "Objects"},
	"📡": {Description: "satellite antenna", Category: "Objects"},
	"🔋": {Description: "battery", Category: "Objects"},
	"🔌": {Description: "electric plug", Category: "Objects"},
	"💡": {Description: "light bulb", Category: "Objects"},
	"🔦": {Description: "flashlight", Category: "Objects"},
	"🕯": {Description: "candle", Category: "Objects"},
	"🗑": {Description: "wastebasket", Category: "Objects"},
	"🛢": {Description: "oil drum", Category: "Objects"},
	"💸": {Description: "money with wings", Category: "Objects"},
	"💵": {Description: "dollar banknote", Category: "Objects"},
	"💴": {Description: "yen banknote", Category: "Objects"},
	"💶": {Description: "euro banknote", Category: "Objects"},
	"💷": {Description: "pound banknote", Category: "Objects"},
	"💰": {Description: "money bag", Category: "Objects"},
	"💳": {Description: "credit card", Category: "Objects"},
	"💎": {Description: "gem stone", Category: "Objects"},
	"⚖️": {Description: "balance scale", Category: "Objects"},
	"🔧": {Description: "wrench", Category: "Objects"},
	"🔨": {Description: "hammer", Category: "Objects"},
	"⚒": {Description: "hammer and pick", Category: "Objects"},
	"🛠": {Description: "hammer and wrench", Category: "Objects"},
	"⛏": {Description: "pick", Category: "Objects"},
	"🔩": {Description: "nut and bolt", Category: "Objects"},
	"⚙️": {Description: "gear", Category: "Objects"},
	"⛓": {Description: "chains", Category: "Objects"},
	"🔫": {Description: "pistol", Category: "Objects"},
	"💣": {Description: "bomb", Category: "Objects"},
	"🔪": {Description: "kitchen knife", Category: "Objects"},
	"🗡": {Description: "dagger", Category: "Objects"},
	"⚔️": {Description: "crossed swords", Category: "Objects"},
	"🛡": {Description: "shield", Category: "Objects"},
	"🚬": {Description: "cigarette", Category: "Objects"},
	"⚰️": {Description: "coffin", Category: "Objects"},
	"⚱️": {Description: "funeral urn", Category: "Objects"},
	"🏺": {Description: "amphora", Category: "Objects"},
	"🔮": {Description: "crystal ball", Category: "Objects"},
	"📿": {Description: "prayer beads", Category: "Objects"},
	"💈": {Description: "barber pole", Category: "Objects"},
	"⚗️": {Description: "alembic", Category: "Objects"},
	"🔭": {Description: "telescope", Category: "Objects"},
	"🔬": {Description: "microscope", Category: "Objects"},
	"🕳": {Description: "hole", Category: "Objects"},
	"💊": {Description: "pill", Category: "Objects"},
	"💉": {Description: "syringe", Category: "Objects"},
	"🌡": {Description: "thermometer", Category: "Objects"},
	"🚽": {Description: "toilet", Category: "Objects"},
	"🚰": {Description: "potable water", Category: "Objects"},
	"🚿": {Description: "shower", Category: "Objects"},
	"🛁": {Description: "bathtub", Category: "Objects"},
	"🛀": {Description: "person taking bath", Category: "Objects"},
	"🛎": {Description: "bellhop bell", Category: "Objects"},
	"🔑": {Description: "key", Category: "Objects"},
	"🗝": {Description: "old key", Category: "Objects"},
	"🚪": {Description: "door", Category: "Objects"},
	"🛋": {Description: "couch and lamp", Category: "Objects"},
	"🛏": {Description: "bed", Category: "Objects"},
	"🛌": {Description: "person in bed", Category: "Objects"},
	"🖼": {Description: "framed picture", Category: "Objects"},
	"🛍": {Description: "shopping bags", Category: "Objects"},
	"🛒": {Description: "shopping cart", Category: "Objects"},
	"🎁": {Description: "wrapped gift", Category: "Objects"},
	"🎈": {Description: "balloon", Category: "Objects"},
	"🎏": {Description: "carp streamer", Category: "Objects"},
	"🎀": {Description: "ribbon", Category: "Objects"},
	"🎊": {Description: "confetti ball", Category: "Objects"},
	"🎉": {Description: "party popper", Category: "Objects"},
	"🎎": {Description: "Japanese dolls", Category: "Objects"},
	"🏮": {Description: "red paper lantern", Category: "Objects"},
	"🎐": {Description: "wind chime", Category: "Objects"},
	"✉️": {Description: "envelope", Category: "Objects"},
	"📩": {Description: "envelope with arrow", Category: "Objects"},
	"📨": {Description: "incoming envelope", Category: "Objects"},
	"📧": {Description: "e-mail", Category: "Objects"},
	"💌": {Description: "love letter", Category: "Objects"},
	"📥": {Description: "inbox tray", Category: "Objects"},
	"📤": {Description: "outbox tray", Category: "Objects"},
	"📦": {Description: "package", Category: "Objects"},
	"🏷": {Description: "label", Category: "Objects"},
	"📪": {Description: "closed mailbox with lowered flag", Category: "Objects"},
	"📫": {Description: "closed mailbox with raised flag", Category: "Objects"},
	"📬": {Description: "open mailbox with raised flag", Category: "Objects"},
	"📭": {Description: "open mailbox with lowered flag", Category: "Objects"},
	"📮": {Description: "postbox", Category: "Objects"},
	"📯": {Description: "postal horn", Category: "Objects"},
	"📜": {Description: "scroll", Category: "Objects"},
	"📃": {Description: "page with curl", Category: "Objects"},
	"📄": {Description: "page facing up", Category: "Objects"},
	"📑": {Description: "bookmark tabs", Category: "Objects"},
	"📊": {Description: "bar chart", Category: "Objects"},
	"📈": {Description: "chart increasing", Category: "Objects"},
	"📉": {Description: "chart decreasing", Category: "Objects"},
	"🗒": {Description: "spiral notepad", Category: "Objects"},
	"🗓": {Description: "spiral calendar", Category: "Objects"},
	"📆": {Description: "tear-off calendar", Category: "Objects"},
	"📅": {Description: "calendar", Category: "Objects"},
	"📇": {Description: "card index", Category: "Objects"},
	"🗃": {Description: "card file box", Category: "Objects"},
	"🗳": {Description: "ballot box with ballot", Category: "Objects"},
	"🗄": {Description: "file cabinet", Category: "Objects"},
	"📋": {Description: "clipboard", Category: "Objects"},
	"📁": {Description: "file folder", Category: "Objects"},
	"📂": {Description: "open file folder", Category: "Objects"},
	"🗂": {Description: "card index dividers", Category: "Objects"},
	"🗞": {Description: "rolled-up newspaper", Category: "Objects"},
	"📰": {Description: "newspaper", Category: "Objects"},
	"📓": {Description: "notebook", Category: "Objects"},
	"📔": {Description: "notebook with decorative cover", Category: "Objects"},
	"📒": {Description: "ledger", Category: "Objects"},
	"📕": {Description: "closed book", Category: "Objects"},
	"📗": {Description: "green book", Category: "Objects"},
	"📘": {Description: "blue book", Category: "Objects"},
	"📙": {Description: "orange book", Category: "Objects"},
	"📚": {Description: "books", Category: "Objects"},
	"📖": {Description: "open book", Category: "Objects"},
	"🔖": {Description: "bookmark", Category: "Objects"},
	"🔗": {Description: "link", Category: "Objects"},
	"📎": {Description: "paperclip", Category: "Objects"},
	"🖇": {Description: "linked paperclips", Category: "Objects"},
	"📐": {Description: "triangular ruler", Category: "Objects"},
	"📏": {Description: "straight ruler", Category: "Objects"},
	"📌": {Description: "pushpin", Category: "Objects"},
	"📍": {Description: "round pushpin", Category: "Objects"},
	"✂️": {Description: "scissors", Category: "Objects"},
	"🖊": {Description: "pen", Category: "Objects"},
	"🖋": {Description: "fountain pen", Category: "Objects"},
	"✒️": {Description: "black nib", Category: "Objects"},
	"🖌": {Description: "paintbrush", Category: "Objects"},
	"🖍": {Description: "crayon", Category: "Objects"},
	"📝": {Description: "memo", Category: "Objects"},
	"✏️": {Description: "pencil", Category: "Objects"},
	"🔍": {Description: "left-pointing magnifying glass", Category: "Objects"},
	"🔎": {Description: "right-pointing magnifying glass", Category: "Objects"},
	"🔏": {Description: "locked with pen", Category: "Objects"},
	"🔐": {Description: "locked with key", Category: "Objects"},
	"🔒": {Description: "locked", Category: "Objects"},
	"🔓": {Description: "unlocked", Category: "Objects"},
	"❤️": {Description: "red heart", Category: "Symbols"},
	"💛": {Description: "yellow heart", Category: "Symbols"},
	"💚": {Description: "green heart", Category: "Symbols"},
	"💙": {Description: "blue heart", Category: "Symbols"},
	"💜": {Description: "purple heart", Category: "Symbols"},
	"🖤": {Description: "black heart", Category: "Symbols"},
	"💔": {Description: "broken heart", Category: "Symbols"},
	"❣️": {Description: "heavy heart exclamation", Category: "Symbols"},
	"💕": {Description: "two hearts", Category: "Symbols"},
	"💞": {Description: "revolving hearts", Category: "Symbols"},
	"💓": {Description: "beating heart", Category: "Symbols"},
	"💗": {Description: "growing heart", Category: "Symbols"},
	"💖": {Description: "sparkling heart", Category: "Symbols"},
	"💘": {Description: "heart with arrow", Category: "Symbols"},
	"💝": {Description: "heart with ribbon", Category: "Symbols"},
	"💟": {Description: "heart decoration", Category: "Symbols"},
	"☮️": {Description: "peace symbol", Category: "Symbols"},
	"✝️": {Description: "latin cross", Category: "Symbols"},
	"☪️": {Description: "star and crescent", Category: "Symbols"},
	"🕉": {Description: "om", Category: "Symbols"},
	"☸️": {Description: "wheel of dharma", Category: "Symbols"},
	"✡️": {Description: "star of David", Category: "Symbols"},
	"🔯": {Description: "dotted six-pointed star", Category: "Symbols"},
	"🕎": {Description: "menorah", Category: "Symbols"},
	"☯️": {Description: "yin yang", Category: "Symbols"},
	"☦️": {Description: "orthodox cross", Category: "Symbols"},
	"🛐": {Description: "place of worship", Category: "Symbols"},
	"⛎": {Description: "Ophiuchus", Category: "Symbols"},
	"♈️": {Description: "Aries", Category: "Symbols"},
	"♉️": {Description: "Taurus", Category: "Symbols"},
	"♊️": {Description: "Gemini", Category: "Symbols"},
	"♋️": {Description: "Cancer", Category: "Symbols"},
	"♌️": {Description: "Leo", Category: "Symbols"},
	"♍️": {Description: "Virgo", Category: "Symbols"},
	"♎️": {Description: "Libra", Category: "Symbols"},
	"♏️": {Description: "Scorpius", Category: "Symbols"},
	"♐️": {Description: "Sagittarius", Category: "Symbols"},
	"♑️": {Description: "Capricorn", Category: "Symbols"},
	"♒️": {Description: "Aquarius", Category: "Symbols"},
	"♓️": {Description: "Pisces", Category: "Symbols"},
	"🆔": {Description: "ID button", Category: "Symbols"},
	"⚛️": {Description: "atom symbol", Category: "Symbols"},
	"🉑": {Description: "Japanese “acceptable” button", Category: "Symbols"},
	"☢️": {Description: "radioactive", Category: "Symbols"},
	"☣️": {Description: "biohazard", Category: "Symbols"},
	"📴": {Description: "mobile phone off", Category: "Symbols"},
	"📳": {Description: "vibration mode", Category: "Symbols"},
	"🈶": {Description: "Japanese “not free of charge” button", Category: "Symbols"},
	"🈚️": {Description: "Japanese “free of charge” button", Category: "Symbols"},
	"🈸": {Description: "Japanese “application” button", Category: "Symbols"},
	"🈺": {Description: "Japanese “open for business” button", Category: "Symbols"},
	"🈷️": {Description: "Japanese “monthly amount” button", Category: "Symbols"},
	"✴️": {Description: "eight-pointed star", Category: "Symbols"},
	"🆚": {Description: "VS button", Category: "Symbols"},
	"💮": {Description: "white flower", Category: "Symbols"},
	"🉐": {Description: "Japanese “bargain” button", Category: "Symbols"},
	"㊙️": {Description: "Japanese “secret” button", Category: "Symbols"},
	"㊗️": {Description: "Japanese “congratulations” button", Category: "Symbols"},
	"🈴": {Description: "Japanese “passing grade” button", Category: "Symbols"},
	"🈵": {Description: "Japanese “no vacancy” button", Category: "Symbols"},
	"🈹": {Description: "Japanese “discount” button", Category: "Symbols"},
	"🈲": {Description: "Japanese “prohibited” button", Category: "Symbols"},
	"🅰️": {Description: "A button (blood type)", Category: "Symbols"},
	"🅱️": {Description: "B button (blood type)", Category: "Symbols"},
	"🆎": {Description: "AB button (blood type)", Category: "Symbols"},
	"🆑": {Description: "CL button", Category: "Symbols"},
	"🅾️": {Description: "O button (blood type)", Category: "Symbols"},
	"🆘": {Description: "SOS button", Category: "Symbols"},
	"❌": {Description: "cross mark", Category: "Symbols"},
	"⭕️": {Description: "heavy large circle", Category: "Symbols"},
	"🛑": {Description: "stop sign", Category: "Symbols"},
	"⛔️": {Description: "no entry", Category: "Symbols"},
	"📛": {Description: "name badge", Category: "Symbols"},
	"🚫": {Description: "prohibited", Category: "Symbols"},
	"💯": {Description: "hundred points", Category: "Symbols"},
	"💢": {Description: "anger symbol", Category: "Symbols"},
	"♨️": {Description: "hot springs", Category: "Symbols"},
	"🚷": {Description: "no pedestrians", Category: "Symbols"},
	"🚯": {Description: "no littering", Category: "Symbols"},
	"🚳": {Description: "no bicycles", Category: "Symbols"},
	"🚱": {Description: "non-potable water", Category: "Symbols"},
	"🔞": {Description: "no one under eighteen", Category: "Symbols"},
	"📵": {Description: "no mobile phones", Category: "Symbols"},
	"🚭": {Description: "no smoking", Category: "Symbols"},
	"❗️": {Description: "exclamation mark", Category: "Symbols"},
	"❕": {Description: "white exclamation mark", Category: "Symbols"},
	"❓": {Description: "question mark", Category: "Symbols"},
	"❔": {Description: "white question mark", Category: "Symbols"},
	"‼️": {Description: "double exclamation mark", Category: "Symbols"},
	"⁉️": {Description: "exclamation question mark", Category: "Symbols"},
	"🔅": {Description: "dim button", Category: "Symbols"},
	"🔆": {Description: "bright button", Category: "Symbols"},
	"〽️": {Description: "part alternation mark", Category: "Symbols"},
	"⚠️": {Description: "warning", Category: "Symbols"},
	"🚸": {Description: "children crossing", Category: "Symbols"},
	"🔱": {Description: "trident emblem", Category: "Symbols"},
	"⚜️": {Description: "fleur-de-lis", Category: "Symbols"},
	"🔰": {Description: "Japanese symbol for beginner", Category: "Symbols"},
	"♻️": {Description: "recycling symbol", Category: "Symbols"},
	"✅": {Description: "white heavy check mark", Category: "Symbols"},
	"🈯️": {Description: "Japanese “reserved” button", Category: "Symbols"},
	"💹": {Description: "chart increasing with yen", Category: "Symbols"},
	"❇️": {Description: "sparkle", Category: "Symbols"},
	"✳️": {Description: "eight-spoked asterisk", Category: "Symbols"},
	"❎": {Description: "cross mark button", Category: "Symbols"},
	"🌐": {Description: "globe with meridians", Category: "Symbols"},
	"💠": {Description: "diamond with a dot", Category: "Symbols"},
	"Ⓜ️": {Description: "circled M", Category: "Symbols"},
	"🌀": {Description: "cyclone", Category: "Symbols"},
	"💤": {Description: "zzz", Category: "Symbols"},
	"🏧": {Description: "ATM sign", Category: "Symbols"},
	"🚾": {Description: "water closet", Category: "Symbols"},
	"♿️": {Description: "wheelchair symbol", Category: "Symbols"},
	"🅿️": {Description: "P button", Category: "Symbols"},
	"🈳": {Description: "Japanese “vacancy” button", Category: "Symbols"},
	"🈂️": {Description: "Japanese “service charge” button", Category: "Symbols"},
	"🛂": {Description: "passport control", Category: "Symbols"},
	"🛃": {Description: "customs", Category: "Symbols"},
	"🛄": {Description: "baggage claim", Category: "Symbols"},
	"🛅": {Description: "left luggage", Category: "Symbols"},
	"🚹": {Description: "men’s room", Category: "Symbols"},
	"🚺": {Description: "women’s room", Category: "Symbols"},
	"🚼": {Description: "baby symbol", Category: "Symbols"},
	"🚻": {Description: "restroom", Category: "Symbols"},
	"🚮": {Description: "litter in bin sign", Category: "Symbols"},
	"🎦": {Description: "cinema", Category: "Symbols"},
	"📶": {Description: "antenna bars", Category: "Symbols"},
	"🈁": {Description: "Japanese “here” button", Category: "Symbols"},
	"🔣": {Description: "input symbols", Category: "Symbols"},
	"ℹ️": {Description: "information", Category: "Symbols"},
	"🔤": {Description: "input latin letters", Category: "Symbols"},
	"🔡": {Description: "input latin lowercase", Category: "Symbols"},
	"🔠": {Description: "input latin uppercase", Category: "Symbols"},
	"🆖": {Description: "NG button", Category: "Symbols"},
	"🆗": {Description: "OK button", Category: "Symbols"},
	"🆙": {Description: "UP! button", Category: "Symbols"},
	"🆒": {Description: "COOL button", Category: "Symbols"},
	"🆕": {Description: "NEW button", Category: "Symbols"},
	"🆓": {Description: "FREE button", Category: "Symbols"},
	"0️⃣": {Description: "keycap: 0", Category: "Symbols"},
	"1️⃣": {Description: "keycap: 1", Category: "Symbols"},
	"2️⃣": {Description: "keycap: 2", Category: "Symbols"},
	"3️⃣": {Description: "keycap: 3", Category: "Symbols"},
	"4️⃣": {Description: "keycap: 4", Category: "Symbols"},
	"5️⃣": {Description: "keycap: 5", Category: "Symbols"},
	"6️⃣": {Description: "keycap: 6", Category: "Symbols"},
	"7️⃣": {Description: "keycap: 7", Category: "Symbols"},
	"8️⃣": {Description: "keycap: 8", Category: "Symbols"},
	"9️⃣": {Description: "keycap: 9", Category: "Symbols"},
	"🔟": {Description: "keycap 10", Category: "Symbols"},
	"🔢": {Description: "input numbers", Category: "Symbols"},
	"#️⃣": {Description: "keycap: #", Category: "Symbols"},
	"*️⃣": {Description: "keycap: *", Category: "Symbols"},
	"▶️": {Description: "play button", Category: "Symbols"},
	"⏸": {Description: "pause button", Category: "Symbols"},
	"⏯": {Description: "play or pause button", Category: "Symbols"},
	"⏹": {Description: "stop button", Category: "Symbols"},
	"⏺": {Description: "record button", Category: "Symbols"},
	"⏭": {Description: "next track button", Category: "Symbols"},
	"⏮": {Description: "last track button", Category: "Symbols"},
	"⏩": {Description: "fast-forward button", Category: "Symbols"},
	"⏪": {Description: "fast reverse button", Category: "Symbols"},
	"⏫": {Description: "fast up button", Category: "Symbols"},
	"⏬": {Description: "fast down button", Category: "Symbols"},
	"◀️": {Description: "reverse button", Category: "Symbols"},
	"🔼": {Description: "up button", Category: "Symbols"},
	"🔽": {Description: "down button", Category: "Symbols"},
	"➡️": {Description: "right arrow", Category: "Symbols"},
	"⬅️": {Description: "left arrow", Category: "Symbols"},
	"⬆️": {Description: "up arrow", Category: "Symbols"},
	"⬇️": {Description: "down arrow", Category: "Symbols"},
	"↗️": {Description: "up-right arrow", Category: "Symbols"},
	"↘️": {Description: "down-right arrow", Category: "Symbols"},
	"↙️": {Description: "down-left arrow", Category: "Symbols"},
	"↖️": {Description: "up-left arrow", Category: "Symbols"},
	"↕️": {Description: "up-down arrow", Category: "Symbols"},
	"↔️": {Description: "left-right arrow", Category: "Symbols"},
	"↪️": {Description: "left arrow curving right", Category: "Symbols"},
	"↩️": {Description: "right arrow curving left", Category: "Symbols"},
	"⤴️": {Description: "right arrow curving up", Category: "Symbols"},
	"⤵️": {Description: "right arrow curving down", Category: "Symbols"},
	"🔀": {Description: "shuffle tracks button", Category: "Symbols"},
	"🔁": {Description: "repeat button", Category: "Symbols"},
	"🔂": {Description: "repeat single button", Category: "Symbols"},
	"🔄": {Description: "anticlockwise arrows button", Category: "Symbols"},
	"🔃": {Description: "clockwise vertical arrows", Category: "Symbols"},
	"🎵": {Description: "musical note", Category: "Symbols"},
	"🎶": {Description: "musical notes", Category: "Symbols"},
	"➕": {Description: "heavy plus sign", Category: "Symbols"},
	"➖": {Description: "heavy minus sign", Category: "Symbols"},
	"➗": {Description: "heavy division sign", Category: "Symbols"},
	"✖️": {Description: "heavy multiplication x", Category: "Symbols"},
	"💲": {Description: "heavy dollar sign", Category: "Symbols"},
	"💱": {Description: "currency exchange", Category: "Symbols"},
	"™️": {Description: "trade mark", Category: "Symbols"},
	"©️": {Description: "copyright", Category: "Symbols"},
	"®️": {Description: "registered", Category: "Symbols"},
	"〰️": {Description: "wavy dash", Category: "Symbols"},
	"➰": {Description: "curly loop", Category: "Symbols"},
	"➿": {Description: "double curly loop", Category: "Symbols"},
	"🔚": {Description: "END arrow", Category: "Symbols"},
	"🔙": {Description: "BACK arrow", Category: "Symbols"},
	"🔛": {Description: "ON! arrow", Category: "Symbols"},
	"🔝": {Description: "TOP arrow", Category: "Symbols"},
	"🔜": {Description: "SOON arrow", Category: "Symbols"},
	"✔️": {Description: "heavy check mark", Category: "Symbols"},
	"☑️": {Description: "ballot box with check", Category: "Symbols"},
	"🔘": {Description: "radio button", Category: "Symbols"},
	"⚪️": {Description: "white circle", Category: "Symbols"},
	"⚫️": {Description: "black circle", Category: "Symbols"},
	"🔴": {Description: "red circle", Category: "Symbols"},
	"🔵": {Description: "blue circle", Category: "Symbols"},
	"🔺": {Description: "red triangle pointed up", Category: "Symbols"},
	"🔻": {Description: "red triangle pointed down", Category: "Symbols"},
	"🔸": {Description: "small orange diamond", Category: "Symbols"},
	"🔹": {Description: "small blue diamond", Category: "Symbols"},
	"🔶": {Description: "large orange diamond", Category: "Symbols"},
	"🔷": {Description: "large blue diamond", Category: "Symbols"},
	"🔳": {Description: "white square button", Category: "Symbols"},
	"🔲": {Description: "black square button", Category: "Symbols"},
	"▪️": {Description: "black small square", Category: "Symbols"},
	"▫️": {Description: "white small square", Category: "Symbols"},
	"◾️": {Description: "black medium-small square", Category: "Symbols"},
	"◽️": {Description: "white medium-small square", Category: "Symbols"},
	"◼️": {Description: "black medium square", Category: "Symbols"},
	"◻️": {Description: "white medium square", Category: "Symbols"},
	"⬛️": {Description: "black large square", Category: "Symbols"},
	"⬜️": {Description: "white large square", Category: "Symbols"},
	"🔈": {Description: "speaker low volume", Category: "Symbols"},
	"🔇": {Description: "muted speaker", Category: "Symbols"},
	"🔉": {Description: "speaker medium volume", Category: "Symbols"},
	"🔊": {Description: "speaker high volume", Category: "Symbols"},
	"🔔": {Description: "bell", Category: "Symbols"},
	"🔕": {Description: "bell with slash", Category: "Symbols"},
	"📣": {Description: "megaphone", Category: "Symbols"},
	"📢": {Description: "loudspeaker", Category: "Symbols"},
	"👁‍🗨": {Description: "eye in speech bubble", Category: "Symbols"},
	"💬": {Description: "speech balloon", Category: "Symbols"},
	"💭": {Description: "thought balloon", Category: "Symbols"},
	"🗯": {Description: "right anger bubble", Category: "Symbols"},
	"♠️": {Description: "spade suit", Category: "Symbols"},
	"♣️": {Description: "club suit", Category: "Symbols"},
	"♥️": {Description: "heart suit", Category: "Symbols"},
	"♦️": {Description: "diamond suit", Category: "Symbols"},
	"🃏": {Description: "joker", Category: "Symbols"},
	"🎴": {Description: "flower playing cards", Category: "Symbols"},
	"🀄️": {Description: "mahjong red dragon", Category: "Symbols"},
	"🕐": {Description: "one o’clock", Category: "Symbols"},
	"🕑": {Description: "two o’clock", Category: "Symbols"},
	"🕒": {Description: "three o’clock", Category: "Symbols"},
	"🕓": {Description: "four o’clock", Category: "Symbols"},
	"🕔": {Description: "five o’clock", Category: "Symbols"},
	"🕕": {Description: "six o’clock", Category: "Symbols"},
	"🕖": {Description: "seven o’clock", Category: "Symbols"},
	"🕗": {Description: "eight o’clock", Category: "Symbols"},
	"🕘": {Description: "nine o’clock", Category: "Symbols"},
	"🕙": {Description: "ten o’clock", Category: "Symbols"},
	"🕚": {Description: "eleven o’clock", Category: "Symbols"},
	"🕛": {Description: "twelve o’clock", Category: "Symbols"},
	"🕜": {Description: "one-thirty", Category: "Symbols"},
	"🕝": {Description: "two-thirty", Category: "Symbols"},
	"🕞": {Description: "three-thirty", Category: "Symbols"},
	"🕟": {Description: "four-thirty", Category: "Symbols"},
	"🕠": {Description: "five-thirty", Category: "Symbols"},
	"🕡": {Description: "six-thirty", Category: "Symbols"},
	"🕢": {Description: "seven-thirty", Category: "Symbols"},
	"🕣": {Description: "eight-thirty", Category: "Symbols"},
	"🕤": {Description: "nine-thirty", Category: "Symbols"},
	"🕥": {Description: "ten-thirty", Category: "Symbols"},
	"🕦": {Description: "eleven-thirty", Category: "Symbols"},
	"🕧": {Description: "twelve-thirty", Category: "Symbols"},
	"🏳️": {Description: "white flag", Category: "Flags"},
	"🏴": {Description: "black flag", Category: "Flags"},
	"🏁": {Description: "chequered flag", Category: "Flags"},
	"🚩": {Description: "triangular flag", Category: "Flags"},
	"🏳️‍🌈": {Description: "rainbow flag", Category: "Flags"},
	"🇦🇫": {Description: "Afghanistan", Category: "Flags"},
	"🇦🇽": {Description: "Åland Islands", Category: "Flags"},
	"🇦🇱": {Description: "Albania", Category: "Flags"},
	"🇩🇿": {Description: "Algeria", Category: "Flags"},
	"🇦🇸": {Description: "American Samoa", Category: "Flags"},
	"🇦🇩": {Description: "Andorra", Category: "Flags"},
	"🇦🇴": {Description: "Angola", Category: "Flags"},
	"🇦🇮": {Description: "Anguilla", Category: "Flags"},
	"🇦🇶": {Description: "Antarctica", Category: "Flags"},
	"🇦🇬": {Description: "Antigua & Barbuda", Category: "Flags"},
	"🇦🇷": {Description: "Argentina", Category: "Flags"},
	"🇦🇲": {Description: "Armenia", Category: "Flags"},
	"🇦🇼": {Description: "Aruba", Category: "Flags"},
	"🇦🇺": {Description: "Australia", Category: "Flags"},
	"🇦🇹": {Description: "Austria", Category: "Flags"},
	"🇦🇿": {Description: "Azerbaijan", Category: "Flags"},
	"🇧🇸": {Description: "Bahamas", Category: "Flags"},
	"🇧🇭": {Description: "Bahrain", Category: "Flags"},
	"🇧🇩": {Description: "Bangladesh", Category: "Flags"},
	"🇧🇧": {Description: "Barbados", Category: "Flags"},
	"🇧🇾": {Description: "Belarus", Category: "Flags"},
	"🇧🇪": {Description: "Belgium", Category: "Flags"},
	"🇧🇿": {Description: "Belize", Category: "Flags"},
	"🇧🇯": {Description: "Benin", Category: "Flags"},
	"🇧🇲": {Description: "Bermuda", Category: "Flags"},
	"🇧🇹": {Description: "Bhutan", Category: "Flags"},
	"🇧🇴": {Description: "Bolivia", Category: "Flags"},
	"🇧🇶": {Description: "Caribbean Netherlands", Category: "Flags"},
	"🇧🇦": {Description: "Bosnia & Herzegovina", Category: "Flags"},
	"🇧🇼": {Description: "Botswana", Category: "Flags"},
	"🇧🇷": {Description: "Brazil", Category: "Flags"},
	"🇮🇴": {Description: "British Indian Ocean Territory", Category: "Flags"},
	"🇻🇬": {Description: "British Virgin Islands", Category: "Flags"},
	"🇧🇳": {Description: "Brunei", Category: "Flags"},
	"🇧🇬": {Description: "Bulgaria", Category: "Flags"},
	"🇧🇫": {Description: "Burkina Faso", Category: "Flags"},
	"🇧🇮": {Description: "Burundi", Category: "Flags"},
	"🇨🇻": {Description: "Cape Verde", Category: "Flags"},
	"🇰🇭": {Description: "Cambodia", Category: "Flags"},
	"🇨🇲": {Description: "Cameroon", Category: "Flags"},
	"🇨🇦": {Description: "Canada", Category: "Flags"},
	"🇮🇨": {Description: "Canary Islands", Category: "Flags"},
	"🇰🇾": {Description: "Cayman Islands", Category: "Flags"},
	"🇨🇫": {Description: "Central African Republic", Category: "Flags"},
	"🇹🇩": {Description: "Chad", Category: "Flags"},
	"🇨🇱": {Description: "Chile", Category: "Flags"},
	"🇨🇳": {Description: "China", Category: "Flags"},
	"🇨🇽": {Description: "Christmas Island", Category: "Flags"},
	"🇨🇨": {Description: "Cocos (Keeling) Islands", Category: "Flags"},
	"🇨🇴": {Description: "Colombia", Category: "Flags"},
	"🇰🇲": {Description: "Comoros", Category: "Flags"},
	"🇨🇬": {Description: "Congo - Brazzaville", Category: "Flags"},
	"🇨🇩": {Description: "Congo - Kinshasa", Category: "Flags"},
	"🇨🇰": {Description: "Cook Islands", Category: "Flags"},
	"🇨🇷": {Description: "Costa Rica", Category: "Flags"},
	"🇨🇮": {Description: "Côte d’Ivoire", Category: "Flags"},
	"🇭🇷": {Description: "Croatia", Category: "Flags"},
	"🇨🇺": {Description: "Cuba", Category: "Flags"},
	"🇨🇼": {Description: "Curaçao", Category: "Flags"},
	"🇨🇾": {Description: "Cyprus", Category: "Flags"},
	"🇨🇿": {Description: "Czech Republic", Category: "Flags"},
	"🇩🇰": {Description: "Denmark", Category: "Flags"},
	"🇩🇯": {Description: "Djibouti", Category: "Flags"},
	"🇩🇲": {Description: "Dominica", Category: "Flags"},
	"🇩🇴": {Description: "Dominican Republic", Category: "Flags"},
	"🇪🇨": {Description: "Ecuador", Category: "Flags"},
	"🇪🇬": {Description: "Egypt", Category: "Flags"},
	"🇸🇻": {Description: "El Salvador", Category: "Flags"},
	"🇬🇶": {Description: "Equatorial Guinea", Category: "Flags"},
	"🇪🇷": {Description: "Eritrea", Category: "Flags"},
	"🇪🇪": {Description: "Estonia", Category: "Flags"},
	"🇪🇹": {Description: "Ethiopia", Category: "Flags"},
	"🇪🇺": {Description: "European Union", Category: "Flags"},
	"🇫🇰": {Description: "Falkland Islands", Category: "Flags"},
	"🇫🇴": {Description: "Faroe Islands", Category: "Flags"},
	"🇫🇯": {Description: "Fiji", Category: "Flags"},
	"🇫🇮": {Description: "Finland", Category: "Flags"},
	"🇫🇷": {Description: "France", Category: "Flags"},
	"🇬🇫": {Description: "French Guiana", Category: "Flags"},
	"🇵🇫": {Description: "French Polynesia", Category: "Flags"},
	"🇹🇫": {Description: "French Southern Territories", Category: "Flags"},
	"🇬🇦": {Description: "Gabon", Category: "Flags"},
	"🇬🇲": {Description: "Gambia", Category: "Flags"},
	"🇬🇪": {Description: "Georgia", Category: "Flags"},
	"🇩🇪": {Description: "Germany", Category: "Flags"},
	"🇬🇭": {Description: "Ghana", Category: "Flags"},
	"🇬🇮": {Description: "Gibraltar", Category: "Flags"},
	"🇬🇷": {Description: "Greece", Category: "Flags"},
	"🇬🇱": {Description: "Greenland", Category: "Flags"},
	"🇬🇩": {Description: "Grenada", Category: "Flags"},
	"🇬🇵": {Description: "Guadeloupe", Category: "Flags"},
	"🇬🇺": {Description: "Guam", Category: "Flags"},
	"🇬🇹": {Description: "Guatemala", Category: "Flags"},
	"🇬🇬": {Description: "Guernsey", Category: "Flags"},
	"🇬🇳": {Description: "Guinea", Category: "Flags"},
	"🇬🇼": {Description: "Guinea-Bissau", Category: "Flags"},
	"🇬🇾": {Description: "Guyana", Category: "Flags"},
	"🇭🇹": {Description: "Haiti", Category: "Flags"},
	"🇭🇳": {Description: "Honduras", Category: "Flags"},
	"🇭🇰": {Description: "Hong Kong SAR China", Category: "Flags"},
	"🇭🇺": {Description: "Hungary", Category: "Flags"},
	"🇮🇸": {Description: "Iceland", Category: "Flags"},
	"🇮🇳": {Description: "India", Category: "Flags"},
	"🇮🇩": {Description: "Indonesia", Category: "Flags"},
	"🇮🇷": {Description: "Iran", Category: "Flags"},
	"🇮🇶": {Description: "Iraq", Category: "Flags"},
	"🇮🇪": {Description: "Ireland", Category: "Flags"},
	"🇮🇲": {Description: "Isle of Man", Category: "Flags"},
	"🇮🇱": {Description: "Israel", Category: "Flags"},
	"🇮🇹": {Description: "Italy", Category: "Flags"},
	"🇯🇲": {Description: "Jamaica", Category: "Flags"},
	"🇯🇵": {Description: "Japan", Category: "Flags"},
	"🎌": {Description: "crossed flags", Category: "Flags"},
	"🇯🇪": {Description: "Jersey", Category: "Flags"},
	"🇯🇴": {Description: "Jordan", Category: "Flags"},
	"🇰🇿": {Description: "Kazakhstan", Category: "Flags"},
	"🇰🇪": {Description: "Kenya", Category: "Flags"},
	"🇰🇮": {Description: "Kiribati", Category: "Flags"},
	"🇽🇰": {Description: "Kosovo", Category: "Flags"},
	"🇰🇼": {Description: "Kuwait", Category: "Flags"},
	"🇰🇬": {Description: "Kyrgyzstan", Category: "Flags"},
	"🇱🇦": {Description: "Laos", Category: "Flags"},
	"🇱🇻": {Description: "Latvia", Category: "Flags"},
	"🇱🇧": {Description: "Lebanon", Category: "Flags"},
	"🇱🇸": {Description: "Lesotho", Category: "Flags"},
	"🇱🇷": {Description: "Liberia", Category: "Flags"},
	"🇱🇾": {Description: "Libya", Category: "Flags"},
	"🇱🇮": {Description: "Liechtenstein", Category: "Flags"},
	"🇱🇹": {Description: "Lithuania", Category: "Flags"},
	"🇱🇺": {Description: "Luxembourg", Category: "Flags"},
	"🇲🇴": {Description: "Macau SAR China", Category: "Flags"},
	"🇲🇰": {Description: "Macedonia", Category: "Flags"},
	"🇲🇬": {Description: "Madagascar", Category: "Flags"},
	"🇲🇼": {Description: "Malawi", Category: "Flags"},
	"🇲🇾": {Description: "Malaysia", Category: "Flags"},
	"🇲🇻": {Description: "Maldives", Category: "Flags"},
	"🇲🇱": {Description: "Mali", Category: "Flags"},
	"🇲🇹": {Description: "Malta", Category: "Flags"},
	"🇲🇭": {Description: "Marshall Islands", Category: "Flags"},
	"🇲🇶": {Description: "Martinique", Category: "Flags"},
	"🇲🇷": {Description: "Mauritania", Category: "Flags"},
	"🇲🇺": {Description: "Mauritius", Category: "Flags"},
	"🇾🇹": {Description: "Mayotte", Category: "Flags"},
	"🇲🇽": {Description: "Mexico", Category: "Flags"},
	"🇫🇲": {Description: "Micronesia", Category: "Flags"},
	"🇲🇩": {Description: "Moldova", Category: "Flags"},
	"🇲🇨": {Description: "Monaco", Category: "Flags"},
	"🇲🇳": {Description: "Mongolia", Category: "Flags"},
	"🇲🇪": {Description: "Montenegro", Category: "Flags"},
	"🇲🇸": {Description: "Montserrat", Category: "Flags"},
	"🇲🇦": {Description: "Morocco", Category: "Flags"},
	"🇲🇿": {Description: "Mozambique", Category: "Flags"},
	"🇲🇲": {Description: "Myanmar (Burma)", Category: "Flags"},
	"🇳🇦": {Description: "Namibia", Category: "Flags"},
	"🇳🇷": {Description: "Nauru", Category: "Flags"},
	"🇳🇵": {Description: "Nepal", Category: "Flags"},
	"🇳🇱": {Description: "Netherlands", Category: "Flags"},
	"🇳🇨": {Description: "New Caledonia", Category: "Flags"},
	"🇳🇿": {Description: "New Zealand", Category: "Flags"},
	"🇳🇮": {Description: "Nicaragua", Category: "Flags"},
	"🇳🇪": {Description: "Niger", Category: "Flags"},
	"🇳🇬": {Description: "Nigeria", Category: "Flags"},
	"🇳🇺": {Description: "Niue", Category: "Flags"},
	"🇳🇫": {Description: "Norfolk Island", Category: "Flags"},
	"🇲🇵": {Description: "Northern Mariana Islands", Category: "Flags"},
	"🇰🇵": {Description: "North Korea", Category: "Flags"},
	"🇳🇴": {Description: "Norway", Category: "Flags"},
	"🇴🇲": {Description: "Oman", Category: "Flags"},
	"🇵🇰": {Description: "Pakistan", Category: "Flags"},
	"🇵🇼": {Description: "Palau", Category: "Flags"},
	"🇵🇸": {Description: "Palestinian Territories", Category: "Flags"},
	"🇵🇦": {Description: "Panama", Category: "Flags"},
	"🇵🇬": {Description: "Papua New Guinea", Category: "Flags"},
	"🇵🇾": {Description: "Paraguay", Category: "Flags"},
	"🇵🇪": {Description: "Peru", Category: "Flags"},
	"🇵🇭": {Description: "Philippines", Category: "Flags"},
	"🇵🇳": {Description: "Pitcairn Islands", Category: "Flags"},
	"🇵🇱": {Description: "Poland", Category: "Flags"},
	"🇵🇹": {Description: "Portugal", Category: "Flags"},
	"🇵🇷": {Description: "Puerto Rico", Category: "Flags"},
	"🇶🇦": {Description: "Qatar", Category: "Flags"},
	"🇷🇪": {Description: "Réunion", Category: "Flags"},
	"🇷🇴": {Description: "Romania", Category: "Flags"},
	"🇷🇺": {Description: "Russia", Category: "Flags"},
	"🇷🇼": {Description: "Rwanda", Category: "Flags"},
	"🇧🇱": {Description: "St. Barthélemy", Category: "Flags"},
	"🇸🇭": {Description: "St. Helena", Category: "Flags"},
	"🇰🇳": {Description: "St. Kitts & Nevis", Category: "Flags"},
	"🇱🇨": {Description: "St. Lucia", Category: "Flags"},
	"🇵🇲": {Description: "St. Pierre & Miquelon", Category: "Flags"},
	"🇻🇨": {Description: "St. Vincent & Grenadines", Category: "Flags"},
	"🇼🇸": {Description: "Samoa", Category: "Flags"},
	"🇸🇲": {Description: "San Marino", Category: "Flags"},
	"🇸🇹": {Description: "São Tomé & Príncipe", Category: "Flags"},
	"🇸🇦": {Description: "Saudi Arabia", Category: "Flags"},
	"🇸🇳": {Description: "Senegal", Category: "Flags"},
	"🇷🇸": {Description: "Serbia", Category: "Flags"},
	"🇸🇨": {Description: "Seychelles", Category: "Flags"},
	"🇸🇱": {Description: "Sierra Leone", Category: "Flags"},
	"🇸🇬": {Description: "Singapore", Category: "Flags"},
	"🇸🇽": {Description: "Sint Maarten", Category: "Flags"},
	"🇸🇰": {Description: "Slovakia", Category: "Flags"},
	"🇸🇮": {Description: "Slovenia", Category: "Flags"},
	"🇸🇧": {Description: "Solomon Islands", Category: "Flags"},
	"🇸🇴": {Description: "Somalia", Category: "Flags"},
	"🇿🇦": {Description: "South Africa", Category: "Flags"},
	"🇬🇸": {Description: "South Georgia & South Sandwich Islands", Category: "Flags"},
	"🇰🇷": {Description: "South Korea", Category: "Flags"},
	"🇸🇸": {Description: "South Sudan", Category: "Flags"},
	"🇪🇸": {Description: "Spain", Category: "Flags"},
	"🇱🇰": {Description: "Sri Lanka", Category: "Flags"},
	"🇸🇩": {Description: "Sudan", Category: "Flags"},
	"🇸🇷": {Description: "Suriname", Category: "Flags"},
	"🇸🇿": {Description: "Swaziland", Category: "Flags"},
	"🇸🇪": {Description: "Sweden", Category: "Flags"},
	"🇨🇭": {Description: "Switzerland", Category: "Flags"},
	"🇸🇾": {Description: "Syria", Category: "Flags"},
	"🇹🇼": {Description: "Taiwan", Category: "Flags"},
	"🇹🇯": {Description: "Tajikistan", Category: "Flags"},
	"🇹🇿": {Description: "Tanzania", Category: "Flags"},
	"🇹🇭": {Description: "Thailand", Category: "Flags"},
	"🇹🇱": {Description: "Timor-Leste", Category: "Flags"},
	"🇹🇬": {Description: "Togo", Category: "Flags"},
	"🇹🇰": {Description: "Tokelau", Category: "Flags"},
	"🇹🇴": {Description: "Tonga", Category: "Flags"},
	"🇹🇹": {Description: "Trinidad & Tobago", Category: "Flags"},
	"🇹🇳": {Description: "Tunisia", Category: "Flags"},
	"🇹🇷": {Description: "Turkey", Category: "Flags"},
	"🇹🇲": {Description: "Turkmenistan", Category: "Flags"},
	"🇹🇨": {Description: "Turks & Caicos Islands", Category: "Flags"},
	"🇹🇻": {Description: "Tuvalu", Category: "Flags"},
	"🇺🇬": {Description: "Uganda", Category: "Flags"},
	"🇺🇦": {Description: "Ukraine", Category: "Flags"},
	"🇦🇪": {Description: "United Arab Emirates", Category: "Flags"},
	"🇬🇧": {Description: "United Kingdom", Category: "Flags"},
	"🇺🇸": {Description: "United States", Category: "Flags"},
	"🇻🇮": {Description: "U.S. Virgin Islands", Category: "Flags"},
	"🇺🇾": {Description: "Uruguay", Category: "Flags"},
	"🇺🇿": {Description: "Uzbekistan", Category: "Flags"},
	"🇻🇺": {Description: "Vanuatu", Category: "Flags"},
	"🇻🇦": {Description: "Vatican City", Category: "Flags"},
	"🇻🇪": {Description: "Venezuela", Category: "Flags"},
	"🇻🇳": {Description: "Vietnam", Category: "Flags"},
	"🇼🇫": {Description: "Wallis & Futuna", Category: "Flags"},
	"🇪🇭": {Description: "Western Sahara", Category: "Flags"},
	"🇾🇪": {Description: "Yemen", Category: "Flags"},
	"🇿🇲": {Description: "Zambia", Category: "Flags"},
	"🇿🇼": {Description: "Zimbabwe", Category: "Flags"},
}