name: Go CI

on:
  push:
    branches-ignore:
      - renovate/**
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+' # Push events to matching v*, i.e. v20.15.10
    paths:
      - '.github/workflows/**.yml'
      - '**/go.*'
      - '**/*.go'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/**.yml'
      - '**/go.*'
      - '**/*.go'

jobs:

  strongo_workflow:
    uses: strongo/go-ci-action/.github/workflows/workflow.yml@main
    permissions:
      contents: write
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
